### ISSUE TITLE
Laravel 5.1.10 fresh install get Invalid hasher [] chosen for Sentry error

### ISSUE THREAD

**Issue by adamriggsy** [intrip/laravel-authentication-acl#101]
When I perform the php artisan authentication:install command I get the following output:
Copied Directory [/vendor/barryvdh/laravel-elfinder/resources/views] To [/resources/views/vendor/elfinder]
Copied File [/vendor/jacopo/authentication-sentry/src/config/config.php] To [/config/cartalyst.sentry.php]
Copied Directory [/vendor/jacopo/authentication-sentry/src/migrations] To [/database/migrations]
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/public/packages/jacopo/laravel-authentication-acl] To [/public/packages/jacopo/laravel-authentication-acl]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_base.php] To [/config/acl_base.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_menu.php] To [/config/acl_menu.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_permissions.php] To [/config/acl_permissions.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_sentry.php] To [/config/acl_sentry.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/resources/views] To [/resources/views/vendor/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/database/migrations] To [/database/migrations]
Copied Directory [/vendor/lavary/laravel-menu/src/Lavary/Menu/resources/views] To [/resources/views/vendor/laravel-menu]
Publishing complete for tag []!
Migration table created successfully.
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle
Migrated: 2014_02_19_095545_create_users_table
Migrated: 2014_02_19_095623_create_user_groups_table
Migrated: 2014_02_19_095637_create_groups_table
Migrated: 2014_02_19_160516_create_permission_table
Migrated: 2014_02_26_165011_create_user_profile_table
Migrated: 2014_05_06_122145_create_profile_field_types
Migrated: 2014_05_06_122155_create_profile_field
Migrated: 2014_10_12_100000_create_password_resets_table

  [InvalidArgumentException]  
  Invalid hasher [] chosen for Sentry.  

Is there something I need to do in order to avoid the InvalidArgumentException or is it really no big deal? I didn't touch any of the config files and the hasher chosen is native.

**Comment by intrip** [comment]
I'll take a look

**Comment by intrip** [comment]
trying to fix that will keep you updated.

**Comment by intrip** [comment]
php artisan vendor:publish should fix the problem. I'll take e deeper look later

**Comment by intrip** [comment]
I think something wrong happened during the install process. Did laravel work if you run php artisan serve?

**Comment by adamriggsy** [comment]
I actually gave up on the whole transition from 4.2 to 5 for now (too many dependencies that don't support 5), but I will test this out a little later and let you know.
