### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by cheles** [intrip/laravel-authentication-acl#105]
Hi,  Is there a view for user to edit/view its profile or needs to be implemented separately?

Thanks

**Comment by intrip** [comment]
If you click on the top-right you should see the edit profile link

**Comment by cheles** [comment]
I did a clean Laravel install and I don;t have any top bar. Is there anything else I should add on welcome.blade.php to show that?

**Comment by intrip** [comment]
When you login in the admin panel you should see a dropdown on the top-right of the screen where you can click on the profile button.
