### ISSUE TITLE
Trying to install into a new project and receive the error 

### ISSUE THREAD

**Issue by elysiopires** [intrip/laravel-authentication-acl#107]
Hello,

I'm trying to install the larval-authentication-acl into a new laravel project(Laravel Framework version 5.1.24 (LTS)), but I always receive the following error:
- jacopo/laravel-authentication-acl 1.3.0 requires laravel/framework 5.0.\* -> no matching package found.
  - Installation request for jacopo/laravel-authentication-acl 1.3.\* -> satisfiable by jacopo/laravel-authentication-acl[1.3.0, 1.3.1, 1.3.10, 1.3.11, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9].

I use Ubuntu Server 14.04.

How can I solve this error?

Thx,
Elysio

**Comment by intrip** [comment]
Which version of the library you're trying to install?

**Comment by elysiopires** [comment]
hello,

I'm trying to install 1.3.\* as informed on the installation guide.

I use laravel 5.1 at last version.

Sincerely,
Elysio

**Comment by intrip** [comment]
Try to use explicitly the version "1.3.13" and tell me if the issue still occur.

**Comment by shinokada** [comment]
I got the same problem with "1.3.13".

```
➜  laravel-auth-acl  composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting     outdated dependencies. Run update to update them. 
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
➜  laravel-auth-acl  composer update
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package jacopo/laravel-authentication-acl could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by intrip** [comment]
you have a typo there, you should use jacopo/laravel-authentication-acl not laravel-auth-acl .
