### ISSUE TITLE
can't install Laravel Framework version 5.2.11

### ISSUE THREAD

**Issue by skeser** [intrip/laravel-authentication-acl#108]
Hi jacopo !
Firstly thx for project.Great job.
i used them your project laravel-5.1.16 its working.
but i have problem; can't install 5.2.11.
1-install latest laravel(5.2.11) with "laravel new project_name" command.
2-i see laravel.
then;
3-open composer.json file, added  "jacopo/laravel-authentication-acl": "1.3.*" line.
## my composer.json file above it.

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2._",
        "laravelcollective/html": "5.2._",
        "jacopo/laravel-authentication-acl": "1.3.*"
##     },

then;
## 4-composer update commad result;

arge@jes82:/var/www/html/lv52.pt$ composer update

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jacopo/laravel-authentication-acl 1.3.9 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.8 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.7 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.6 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.5 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.4 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.3 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.2 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.11 requires laravel/framework 5.0._|5.1._ -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.10 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.1 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.0 requires laravel/framework 5.0.\* -> no matching package found.
    - Installation request for jacopo/laravel-authentication-acl 1.3.\* -> satisfiable by jacopo/laravel-authentication-acl[1.3.0, 1.3.1, 1.3.10, 1.3.11, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
## Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

can u help me please ?
can u upgrade your project for laravel 5.2.11 ?
thx.

**Comment by webdesign7** [comment]
any updates ?

**Comment by skeser** [comment]
not yet..

**Comment by intrip** [comment]
I'll take a look next week

**Comment by intrip** [comment]
After taking a fast look in order to make the package work with Laravel 5.2 I need to do some refactoring and code changes so could take a while. 
Will keep you updated.

**Comment by webdesign7** [comment]
okay .. thank you

**Comment by skeser** [comment]
i will waiting for your upgraded..
thx a lot jacopo. :+1: 
I can help turkish translation this project, if you want this.

**Comment by intrip** [comment]
I've pushed a new version (1.3.12) that works well with Laravel 5.2. Please give me some feedback!
Backward compatibility with 5.1 and 5.0 version is not handled. If you need to use an older Laravel 5 version use the 1.3.11 version of the package.

**Comment by skeser** [comment]
My test system;
Linux jes82 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 
PHP Version 5.6.14-0+deb8u1

**According to "ACL documentation" step by step.**

1-Install laravel latest version, see "Laravel 5".

php artisan --version
Laravel Framework version 5.2.13

2-Set database for change .env files.

3-change composer.json file, add "jacopo/laravel-authentication-acl": "1.3.*"

4-Run : root@jes82:/var/www/html/lvtest2.pt# composer install

## Result is;

Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
    Nothing to install or update
    Generating autoload files
    > php artisan clear-compiled
    > php artisan optimize
    Generating optimized class loader

---

Opss ! Nothing to install or update ! then;

5-Run : root@jes82:/var/www/html/lvtest2.pt# composer update

## Result is;

> php artisan clear-compiled
>     Loading composer repositories with package information
>     Updating dependencies (including require-dev)
>       - Installing gregwar/captcha (v1.0.11)
>         Loading from cache

```
  - Installing jacopo/authentication-sentry (1.0.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.2.2)
    Downloading: 100%

  - Installing intervention/image (2.3.5)
    Downloading: 100%

  - Installing laravelcollective/html (v5.2.4)
    Downloading: 100%

  - Installing jacopo/laravel-authentication-acl (1.3.12)
    Downloading: 100%

jacopo/authentication-sentry suggests installing ircmaxell/password-compat (Default hashing uses PHP 5.5 password_* functions, with forward-compatible support.)
jacopo/authentication-sentry suggests installing happydemon/txt (Required Text helpers when using the Kohana implementation)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "CreateUsersTable" was found in both "$baseDir .'/database/migrations/2014_10_12_000000_create_users_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_02_19_095545_create_users_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreatePasswordResetsTable" was found in both "$baseDir . '/database/migrations/2014_10_12_100000_create_password_resets_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_10_12_100000_create_password_resets_table.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsers" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225921_ migration_cartalyst_sentry_install_users.php", the first will be used.Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallGroups" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php" and "/var/w                                           ww/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallThrottle" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsersGroupsPivot"was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migra tions/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php", the first will be used.
> php artisan optimize
Generating optimized class loader
```

---

I have a lot of warnings :)
6-Run:root@jes82:/var/www/html/lvtest2.pt# composer install

## Result is;

Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Nothing to install or update
    Generating autoload files
    Warning: Ambiguous class resolution, "CreateUsersTable" was found in both "$baseDir.'/database/migrations/2014_10_12_000000_create_users_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_02_19_095545_create_users_table.php", the first will be used.
    Warning: Ambiguous class resolution, "CreatePasswordResetsTable" was found in both "$baseDir . '/database/migrations/2014_10_12_100000_create_password_resets_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_10_12_100000_create_password_resets_table.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsers" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallGroups" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallThrottle" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsersGroupsPivot" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php", the first will be used.
    > php artisan clear-compiled
    > php artisan optimize
    Generating optimized class loader

---

7-I'm open the file config/app.php and add to the 'providers' option the line: `'LaravelAcl\Authentication\AuthenticationServiceProvider',`

8-Run:root@jes82:/var/www/html/lvtest2.pt# php artisan authentication:install

## Result is;

```
Copied File [/vendor/jacopo/authentication-sentry/src/config/config.php] To [/config/cartalyst.sentry.php]
Copied Directory [/vendor/jacopo/authentication-sentry/src/migrations] To [/database/migrations]
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/public/packages/jacopo/laravel-authentication-acl] To [/public/packages/jacopo/laravel-authentication-acl]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_base.php] To [/config/acl_base.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_menu.php] To [/config/acl_menu.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_permissions.php] To [/config/acl_permissions.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_sentry.php] To [/config/acl_sentry.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/resources/views] To [/resources/views/vendor/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Migration table created successfully.
PHP Fatal error:  Cannot redeclare class CreateUsersTable in /var/www/html/lvtest2.pt/database/migrations/2014_10_12_000000_create_users_table.php on line 34


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot redeclare class CreateUsersTable
```

---

Cannot redeclare class !! My solution;

9-Delete dublicated 2014_10_12_000000_create_users_table.php file.
This file coming laravel installation.Location is "database\migrations"

10-root@jes82:/var/www/html/lvtest2.pt# php artisan authentication:install

## Result is;

Copied Directory [/vendor/jacopo/authentication-sentry/src/migrations] To [/database/migrations]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/public/packages/jacopo/laravel-authentication-acl] To [/public/packages/jacopo/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/resources/views] To [/resources/views/vendor/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle
Migrated: 2014_02_19_095545_create_users_table
Migrated: 2014_02_19_095623_create_user_groups_table
Migrated: 2014_02_19_095637_create_groups_table
Migrated: 2014_02_19_160516_create_permission_table
Migrated: 2014_02_26_165011_create_user_profile_table
Migrated: 2014_05_06_122145_create_profile_field_types
Migrated: 2014_05_06_122155_create_profile_field
Migrated: 2014_10_12_100000_create_password_resets_table

## Laravel Authentication ACL Installed successfully

---

yep see successfully:)
But :/

11-Open the browser and go, http://lvtest2.pt/login

## Result is;

 2/2 ErrorException in 604ec0af7cf42fa39ad048cb3593a0b8e31f5a9b.php line 15: Undefined variable: errors (View: /var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/client/auth/login.blade.php) 

and

 1/2 ErrorException in 604ec0af7cf42fa39ad048cb3593a0b8e31f5a9b.php line 15: Undefined variable: errors 

---

Okay, try admin page,
 ops :)
12-Open the browser and go, http://lvtest2.pt/admin/login

## Result is;

2/2 ErrorException in 3c1e564055296adfdaefe6193f4e7264007620e7.php line 15: Undefined variable: errors (View: /var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/admin/auth/login.blade.php) 
and
 1/2 ErrorException in 3c1e564055296adfdaefe6193f4e7264007620e7.php line 15: Undefined variable: errors 

---

My solution is;(not correct but try it.)
Open this file "/var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/admin/auth/login.blade.php"

## and delete the fallowing line.

 @if($errors && ! $errors->isEmpty() )
                @foreach($errors->all() as $error)
                <div class="alert alert-danger">{{$error}}</div>
                @endforeach
                @endif

---

didn't work :)
another error:
`"Class 'Form' not found"`
and stopped, write this message..
**I want really fix above errors and contribute your project but i'm new a laravel,learning a head.may be couple of months do this.I hope.
Thx again for write this project.
What are you think about my message

**Comment by intrip** [comment]
Allright i think is a problem with authentication_sentry dependency. I'll fix that

Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Sevket Keser notifications@github.com </div><div>Data:02/02/2016  21:10  (GMT+01:00) </div><div>A: intrip/laravel-authentication-acl laravel-authentication-acl@noreply.github.com </div><div>Cc: jacopo beschi.jacopo@gmail.com </div><div>Oggetto: Re: [laravel-authentication-acl] can't install Laravel Framework
  version 5.2.11 (#108) </div><div>
</div>My test system;

Linux jes82 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 
PHP Version 5.6.14-0+deb8u1
According to "ACL documentation" step by step.

1-Install laravel latest version, see "Laravel 5".

php artisan --version
Laravel Framework version 5.2.13
2-Set database for change .env files.

3-change composer.json file, add "jacopo/laravel-authentication-acl": "1.3.*"

4-Run : root@jes82:/var/www/html/lvtest2.pt# composer install

Result is;

``````
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader

---------------------------------------------------------------
Opss ! Nothing to install or update ! then;

5-Run : root@jes82:/var/www/html/lvtest2.pt# composer update
Result is;
---------------------------------------------------------------
    ```
> php artisan clear-compiled
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
      - Installing gregwar/captcha (v1.0.11)
        Loading from cache

      - Installing jacopo/authentication-sentry (1.0.0)
        Loading from cache

      - Installing psr/http-message (1.0)
        Loading from cache

      - Installing guzzlehttp/psr7 (1.2.2)
        Downloading: 100%

      - Installing intervention/image (2.3.5)
        Downloading: 100%

      - Installing laravelcollective/html (v5.2.4)
        Downloading: 100%

      - Installing jacopo/laravel-authentication-acl (1.3.12)
        Downloading: 100%

    jacopo/authentication-sentry suggests installing ircmaxell/password-compat (Default hashing uses PHP 5.5 password_* functions, with forward-compatible support.)
    jacopo/authentication-sentry suggests installing happydemon/txt (Required Text helpers when using the Kohana implementation)
    intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
    intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
    Writing lock file
    Generating autoload files
    Warning: Ambiguous class resolution, "CreateUsersTable" was found in both "$baseDir .'/database/migrations/2014_10_12_000000_create_users_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_02_19_095545_create_users_table.php", the first will be used.
    Warning: Ambiguous class resolution, "CreatePasswordResetsTable" was found in both "$baseDir . '/database/migrations/2014_10_12_100000_create_password_resets_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_10_12_100000_create_password_resets_table.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsers" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225921_ migration_cartalyst_sentry_install_users.php", the first will be used.Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallGroups" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php" and "/var/w                                           ww/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallThrottle" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php", the first will be used.
    Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsersGroupsPivot"was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migra tions/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php", the first will be used.
    > php artisan optimize
    Generating optimized class loader
I have a lot of warnings :)
6-Run:root@jes82:/var/www/html/lvtest2.pt# composer install

Result is;

``````

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Warning: Ambiguous class resolution, "CreateUsersTable" was found in both "$baseDir.'/database/migrations/2014_10_12_000000_create_users_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_02_19_095545_create_users_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreatePasswordResetsTable" was found in both "$baseDir . '/database/migrations/2014_10_12_100000_create_password_resets_table.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_10_12_100000_create_password_resets_table.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsers" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225921_migration_cartalyst_sentry_install_users.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallGroups" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225929_migration_cartalyst_sentry_install_groups.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallThrottle" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225988_migration_cartalyst_sentry_install_throttle.php", the first will be used.
Warning: Ambiguous class resolution, "MigrationCartalystSentryInstallUsersGroupsPivot" was found in both "/var/www/html/lvtest2.pt/vendor/jacopo/laravel-authentication-acl/database/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php" and "/var/www/html/lvtest2.pt/vendor/jacopo/authentication-sentry/src/migrations/2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot.php", the first will be used.

> php artisan clear-compiled
> php artisan optimize
> Generating optimized class loader

---

7-I'm open the file config/app.php and add to the 'providers' option the line: `'LaravelAcl\Authentication\AuthenticationServiceProvider',`

8-Run:root@jes82:/var/www/html/lvtest2.pt# php artisan authentication:install

## Result is;

Copied File [/vendor/jacopo/authentication-sentry/src/config/config.php] To [/config/cartalyst.sentry.php]
Copied Directory [/vendor/jacopo/authentication-sentry/src/migrations] To [/database/migrations]
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/public/packages/jacopo/laravel-authentication-acl] To [/public/packages/jacopo/laravel-authentication-acl]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_base.php] To [/config/acl_base.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_menu.php] To [/config/acl_menu.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_permissions.php] To [/config/acl_permissions.php]
Copied File [/vendor/jacopo/laravel-authentication-acl/config/acl_sentry.php] To [/config/acl_sentry.php]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/resources/views] To [/resources/views/vendor/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Migration table created successfully.
PHP Fatal error:  Cannot redeclare class CreateUsersTable in /var/www/html/lvtest2.pt/database/migrations/2014_10_12_000000_create_users_table.php on line 34

  [Symfony\Component\Debug\Exception\FatalErrorException]

##   Cannot redeclare class CreateUsersTable

Cannot redeclare class !! My solution;

9-Delete dublicated 2014_10_12_000000_create_users_table.php file.
This file coming laravel installation.Location is "database\migrations"

9-root@jes82:/var/www/html/lvtest2.pt# php artisan authentication:install

## Result is;

Copied Directory [/vendor/jacopo/authentication-sentry/src/migrations] To [/database/migrations]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/public/packages/jacopo/laravel-authentication-acl] To [/public/packages/jacopo/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/resources/views] To [/resources/views/vendor/laravel-authentication-acl]
Copied Directory [/vendor/jacopo/laravel-authentication-acl/database/migrations] To [/database/migrations]
Publishing complete for tag []!
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle
Migrated: 2014_02_19_095545_create_users_table
Migrated: 2014_02_19_095623_create_user_groups_table
Migrated: 2014_02_19_095637_create_groups_table
Migrated: 2014_02_19_160516_create_permission_table
Migrated: 2014_02_26_165011_create_user_profile_table
Migrated: 2014_05_06_122145_create_profile_field_types
Migrated: 2014_05_06_122155_create_profile_field
Migrated: 2014_10_12_100000_create_password_resets_table

Laravel Authentication ACL Installed successfully

---

yep see successfully:)
But :/

10-Open the browser and go, http://lvtest2.pt/login

## Result is;

2/2 ErrorException in 604ec0af7cf42fa39ad048cb3593a0b8e31f5a9b.php line 15: Undefined variable: errors (View: /var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/client/auth/login.blade.php)

and

1/2 ErrorException in 604ec0af7cf42fa39ad048cb3593a0b8e31f5a9b.php line 15: Undefined variable: errors 

---

Okay, try admin page,
 ops :)
11-Open the browser and go, http://lvtest2.pt/admin/login

## Result is;

2/2 ErrorException in 3c1e564055296adfdaefe6193f4e7264007620e7.php line 15: Undefined variable: errors (View: /var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/admin/auth/login.blade.php) 
and
1/2 ErrorException in 3c1e564055296adfdaefe6193f4e7264007620e7.php line 15: Undefined variable: errors 

---

My solution is;(correct but try it.)
Open this file "/var/www/html/lvtest2.pt/resources/views/vendor/laravel-authentication-acl/admin/auth/login.blade.php"

## and delete the fallowing line.

@if($errors && ! $errors->isEmpty() )
@foreach($errors->all() as $error)
{{$error}}

@endforeach

## @endif

didn't work :)
another error:
`"Class 'Form' not found"`
and stopped, write this message..
**I want really fix above errors and contribute your project but i'm new a laravel,learning a head.may be couple of months do this.I hope.
Thx again for write this project.
What are you think about my message

**Comment by intrip** [comment]
I think it's fixed now. just do a composer update (check for version 1.3.13) and also  
Open the file _app/Http/Kernel.php_ and add the following lines to your $routeMiddleware array: 
             'admin_logged' => \LaravelAcl\Http\Middleware\AdminLogged::class,
             'logged' => \LaravelAcl\Http\Middleware\Logged::class,
             'can_see' => \LaravelAcl\Http\Middleware\CanSee::class,
             'has_perm' => \LaravelAcl\Http\Middleware\HasPerm::class,

Give me some feedback.

**Comment by chameeragb** [comment]
Hi @intrip , I also face this issue when installing acl with laravel 5.2. 

```
Warning: Ambiguous class resolution, "CreatePasswordResetsTable" was found in both "$baseDir . '/database/migrations/2014_10_12_100000_create_password_resets_table.php" and "/opt/lampp/htdocs/laravelapps/testacl/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_10_12_100000_create_password_resets_table.php", the first will be used.
Warning: Ambiguous class resolution, "CreateUsersTable" was found in both "$baseDir . '/database/migrations/2014_10_12_000000_create_users_table.php" and "/opt/lampp/htdocs/laravelapps/testacl/vendor/jacopo/laravel-authentication-acl/database/migrations/2014_02_19_095545_create_users_table.php", the first will be used.

```

Following is my composer.json configuration.

```
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "5.2.",
        "jacopo/laravel-authentication-acl": "1.3.*"
    },
```

Kindly let me know how to resolve this issue.

**Comment by skeser** [comment]
chameeragb : before install lacl,you must be delete both tabe.
"create_password_resets_table" and "create_users_table"
