### ISSUE TITLE
user editor vs profile type editor

### ISSUE THREAD

**Issue by karelv** [intrip/laravel-authentication-acl#11]
After creating fresh laravel project (4.2), I followed the install instructions for this package (1.1.3).

So I played a bit with it, just checking if I could give a regular user only the editor for "profile type editor" in the admin area of your package.
It seems not possible (I didn't do any code changes).

When I give that user permission for user editor, he got both user and profile type editor.

**Comment by intrip** [comment]
Yes you're right, at the moment it's not handled well this case. I'll handle that better in next release soon. Thanks for help.

**Comment by intrip** [comment]
Actually i've changed my mind and i'm not gonna implement that for now. Maybie in version 2.*
In fact i think this is a rare case and shouldn't affect much the software behaviour.
