### ISSUE TITLE
Undefined Variable error

### ISSUE THREAD

**Issue by daviskoko** [intrip/laravel-authentication-acl#110]
Hi, after installing the whole thing using composer,
am getting these errors when url is pointed to admin/login & login respectively,
Undefined variable: errors (View: C:\wamp\www\mysite\resources\views\vendor\laravel-authentication-acl\admin\auth\login.blade.php)
Undefined variable: errors (View: C:\wamp\www\mysite\resources\views\vendor\laravel-authentication-acl\client\auth\login.blade.php)
And for user/signup, it gives this error
Class 'HTML' not found

Note: its a fresh laravel v5.2.13

**Comment by jopi2016** [comment]
you need to add in routes.php before the line
Route::get('/admin/login', [
the line
Route::group(['middleware' => ['web']], function () {

Furthermore before the line
//////////////////// Automatic error handling //////////////////////////
add
});

**Comment by jopi2016** [comment]
But then I get the next issue -> class Form does not exist
This is because some stuff in Larevel 5 got deprecated/unsupported
I then tried https://laravelcollective.com/docs/5.1/html#installation (because of https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-illuminatefoundationapplicationbindshared-1/replies/135768)

**Comment by aldozumaran** [comment]
@jopi2016 Hi
Added Route::group(['middleware' => ['web']], function () { }); to routes.php
Added to congfig/app.php LaravelCollective Config
'providers' => [
    // ...
    Collective\Html\HtmlServiceProvider::class,
    // ...
  ],
'aliases' => [
    // ...
      'Form' => Collective\Html\FormFacade::class,
      'Html' => Collective\Html\HtmlFacade::class,
    // ...
  ],

but now i have this issue:  class Html does not exist

**Comment by jopi2016** [comment]
Yes,
I run into the same issue :-(

**Comment by intrip** [comment]
Working on it.

**Comment by aldozumaran** [comment]
@jopi2016  set **HTML** instead '**Html**' => Collective\Html\HtmlFacade::class, and works

@intrip  Laravel non carica la configurazione!

**Comment by intrip** [comment]
Should be fixed now (version 1.3.13) remember to open the file _app/Http/Kernel.php_ and add the following lines to your $routeMiddleware array: 
             'admin_logged' => \LaravelAcl\Http\Middleware\AdminLogged::class,
             'logged' => \LaravelAcl\Http\Middleware\Logged::class,
             'can_see' => \LaravelAcl\Http\Middleware\CanSee::class,
             'has_perm' => \LaravelAcl\Http\Middleware\HasPerm::class,

**Comment by aldozumaran** [comment]
it works
