### ISSUE TITLE
Doesn't work pagination to the users list

### ISSUE THREAD

**Issue by vampyar** [intrip/laravel-authentication-acl#111]
Doesn't work pagination to the users list, shows always all user list, could you a fix ???
version 1.2 for laravel 4.2

**Comment by intrip** [comment]
The default users_per page are 15. You can change that with the configuration file as the doc says.

**Comment by vampyar** [comment]
Okay, but when clicked on the 2 page or 3 page get 1 page

**Comment by vampyar** [comment]
Content doesn't change

**Comment by intrip** [comment]
You using the 1.2-dev version or a tagged one?

**Comment by vampyar** [comment]
I'm using the 1.2 for laravel 4.2///

2016-02-05 10:17 GMT+02:00 jacopo notifications@github.com:

**Comment by gamingumar** [comment]
is there any workaround to this?

**Comment by gamingumar** [comment]
hi @intrip thanks for your amazing ACL package for laravel. Pagination is really very simple in laravel by just using paginate function, kindly fix it asap

**Comment by klin34970** [comment]
example? try with the paginate function didn't work.

**Comment by intrip** [comment]
I'm not supporting bugfixes for the Laravel 4.2 version  sorry.
