### ISSUE TITLE
Getting error when custom_fields is created...

### ISSUE THREAD

**Issue by snipiba** [intrip/laravel-authentication-acl#112]
Argument 1 passed to Illuminate\Database\Grammar::parameterize() ...
ErrorException in Grammar.php line 118:

**Comment by intrip** [comment]
Should be fixed with version 1.3.13, also remember to read the updated install doc.

**Comment by snipiba** [comment]
when i get [0] to CustomProfileRepository at lines approx 75 & 112
`"profile_id"            => $this->profile_id[0],`
and
`return ProfileField::where('profile_id', $this->profile_id[0])`
then i not get error.. i think, is caused by making call to create custom_profile_repository with
`$custom_profile_repository = App::make('custom_profile_repository', [$user_profile->id]);`

created array... then custom_profile_repository (on constructor waiting profile_id) get [profile_id] as array... and this is (maybe) the main problem. what u mean?

**Comment by intrip** [comment]
I see your point, taking a look

**Comment by intrip** [comment]
Try with the new version 1.3.14, should be fixed now.

**Comment by intrip** [comment]
I've realized there is a problem with flash messages, you see them correctly?
