### ISSUE TITLE
Error composer update

### ISSUE THREAD

**Issue by 777genius** [intrip/laravel-authentication-acl#123]
[RuntimeException]
Could not load package intervention/image in http://packagist.org:
tedValueException] Could not parse version constraint 4.x.x: Invali
n string "4.x.x"

[UnexpectedValueException]
Could not parse version constraint 4.x.x: Invalid version string "4

**Comment by 777genius** [comment]
```
    "laravel/framework": "5.2.*",
    "jacopo/laravel-authentication-acl": "1.3.*"
```

**Comment by intrip** [comment]
Something is wrong with your composer.json: do you have included manually intervention/image?

**Comment by Cyberiaaxis** [comment]
by "composer self-update" the error is gone

**Comment by 777genius** [comment]
It was an old version of composer

**Comment by Cyberiaaxis** [comment]
yes (more then 60 days)

**Comment by intrip** [comment]
Allright.
