### ISSUE TITLE
not easy for beginner !!

### ISSUE THREAD

**Issue by DavidMagdi** [intrip/laravel-authentication-acl#124]
first of all  i would like to thank you for the great work you have done ,

but May you make videos or make full Wiki for documentation and usage

```
> // resources/views/layouts/app.blade.php
> 
> <!DOCTYPE html>
> <html lang="en">
>     <head>
>         <title>Laravel Quickstart - Intermediate</title>
```

on  comment block shows where the code goes and looks .

or Sample pages  like Demo for beginners like me 

i spent full 4 days trying to get everything work  but all i get like 10% of what my project need and ends with find my self  moving from laracast forum  to stackoverflow .

thanks in Advanced

**Comment by DavidMagdi** [comment]
I'm trying to get authenticated user id  into blade to insert it into record on database i tried a lost ,almost everything and cant get it to work !!!

**Comment by gamingumar** [comment]
Read the docs, you can do that using authenticator class.
From your controller you can get the logged user and pass it to the view,

```
$logged_user = App::make('authenticator')->getLoggedUser();
return view('your_view', compact('logged_user');
```
