### ISSUE TITLE
Laravel 5.3 Compatibility

### ISSUE THREAD

**Issue by Gittinhub** [intrip/laravel-authentication-acl#131]
Hi.

Laravel 5.3 will be released in a few days.

I would like to know if this current version is compatible or a commit is needed to upgrade? 
If some change has to be made, when it's gonna be done?

Regards

**Comment by jacopo-beschi-intersail** [comment]
Can't answer you yet. I'll take a look and tell you.

**Comment by Gittinhub** [comment]
Ok. 
I will be waiting.

**Comment by intrip** [comment]
I'll make it work with 5.3 when will be released as stable.
