### ISSUE TITLE
User relation

### ISSUE THREAD

**Issue by rasadeghnasab** [intrip/laravel-authentication-acl#134]
I need a function in my User model e.g.:

```
public function posts() {
    return $this->hasMany('App\Post');
  }
```

And I want to use it this way.
`$user->albums`
Where $user is equal to authenticated user.
How can I do that and what is the best way to get authenticated user in order to use it anywhere?

**Comment by gamingumar** [comment]
`$user = App::make('authenticator')->getLoggedUser();`
This will return you currently logged in user
