### ISSUE TITLE
Routes - not a issue

### ISSUE THREAD

**Issue by eughenio** [intrip/laravel-authentication-acl#14]
Hello @intrip, How are you?

I have a question, 

How can I put all my routes to only logged users can be able to access?
I changed my app/routes.php as below and are not working, the user keeps being redirected to /login:

``` php
    Route::group(['before' => 'auth'], function ()
    {
            Route::get('/', function()
                {
                    return View::make('hello');
               }
            );
    });
```

**Comment by intrip** [comment]
Route::group(['before' => ['logged']], function ()
{

// put your routes here.

});

**Comment by eughenio** [comment]
Hi @intrip,

Sorry, I was not clear.

I would like to put all my routes outside the admin only to logged users.
If I put the 'before' => ['logged'], I will be redirected to admin/login but I would like if a user not logged i would like to be redirected to the /login.

Should I create another filter?
If yes, Do you recommend I create in app/filter or vendor/jacopo/...../filter?

Fantastic work.

**Comment by intrip** [comment]
You could add this to your app/filters.php:

```
Route::filter('client_logged', function()
{
    if (! App::make('authenticator')->check()) return Redirect::to('/login');
});
```

Ill add that new filter on the package soon.

**Comment by eughenio** [comment]
Perfect, Thanks a lot.
