### ISSUE TITLE
Foreign key checks error

### ISSUE THREAD

**Issue by adifaidz** [intrip/laravel-authentication-acl#141]
I got this error when trying to add a user

`SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near '='.`

I'm using the sqlsrv driver, i tried to add 'sqlsrv' to the driver list in DBHelper class and it works for now. Is this a good way to do it or not? Sorry, I'm pretty new to github

**Comment by intrip** [comment]
Can you post the code example?

**Comment by adifaidz** [comment]
```
<?php  namespace LaravelAcl\Authentication\Helpers;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use PDO;

class DbHelper
{
    /**
     * Drivers that doesn't support foreign keys check
     * @var array
     */
    public static $no_foreign_keys_drivers = ['sqlite', 'pgsql', 'sqlsrv'];
```

I added the sqlsrv to the $no_foreign_keys_drivers

**Comment by intrip** [comment]
Closing this then
