### ISSUE TITLE
Laravel Policy issue

### ISSUE THREAD

**Issue by rasadeghnasab** [intrip/laravel-authentication-acl#144]
I want to use laravel Gate facade and I almos eveything is correct but when I call 
`Gate::allows('edit Or other method', $lesson);` nothing happens.
I call Gate with this way 
`Gate::forUser(\App::make('authenticator')->getLoggedUser())->allows('edit Or other method', $lesson)`
and it works. I think it has a problem with this package authentication. Does anyone knows anything about this problem?

**Comment by intrip** [comment]
That should be because the user model is not the same as the default laravel model.

**Comment by rasadeghnasab** [comment]
@intrip How can I do that? I mean, how can I change laravel user model to athenticator user model?
