### ISSUE TITLE
got error in step 6 for setup

### ISSUE THREAD

**Issue by alirayaneh** [intrip/laravel-authentication-acl#15]
I've using "jacopo/laravel-authentication-acl" i get last version from github .. when i trid to setup it all step is corectly but step 6 when i run command "php artisan authentication:install" get errors below:

[illuminate\Database\QueryException] SQLSTATE [4200]: Syntax error or access violation :1103 Incorect table name '' <SQL :creat table '' <'migration' varchar(255) nut null , 'batch' int not null defult charecter set utf8 collate utf8_unicode_ci>

im using mysql and set defult='mysql' in app/config/database.php

first :download laravel-authentication-acl-master.zip from gathub Then all step like Guide doc that here https://github.com/intrip/laravel-authentication-acl/blob/master/docs/index.md but in step 6 get error... Even I got a copy from 'app/migrations' to 'app/databas/migrations' then when i run 'php artisan migrate' get error

**Comment by intrip** [comment]
Try to remove completely _vendor/jacopo_ folder an run _composer update_. 
Then try to install again the app, if the problem still occur please post me the full error message.

**Comment by alirayaneh** [comment]
i got remove all project folder then creat a new laravel project then copy your pack in to larvavel project folder www/laravel 

# then run 'composer update' with this compser.json content 

{
  "name": "jacopo/laravel-authentication-acl",
  "description": "Laravel authentication and ACL package with a cool admin panel",
  "license": "MIT",
  "keywords": ["acl", "authentication", "signup", "admin panel", "profile", "laravel"],
  "authors": [
    {
      "name": "jacopo",
      "email": "jacopo@jacopobeschi.com",
      "homepage": "http://www.jacopobeschi.com"
    }
  ],
  "repositories": [
    {
      "type": "vcs",
      "url": "git://github.com/orchestral/phpseclib.git"
    }
  ],
  "require": {
    "php": ">=5.4.0",
    "illuminate/support": "~4",
    "intervention/image": "2._",
    "cartalyst/sentry": "2.1._",
    "jacopo/laravel-library": "1.0._",
    "gregwar/captcha": "1.0.11",
    "jacopo/laravel-authentication-acl": "1.1.0"
  },
  "require-dev": {
    "mockery/mockery": "0.9.0",
    "orchestra/testbench": "2.2._",
    "doctrine/dbal": "v2.4.2",
    "fzaninotto/faker": "v1.3.0",
    "behat/behat": "2.5._@stable",
    "behat/mink-extension": "_",
    "behat/mink-goutte-driver": "*"
  },
  "autoload": {
    "psr-0": {
      "Jacopo\Authentication": "src/"
    },
    "psr-4": {
      "Jacopo\Authentication\Tests\": "tests/"
    },
    "classmap": [
      "src/controllers",
      "src/commands",
      "src/seeds"
    ]
  },
  "minimum-stability": "stable"

# }

## then show this blow error:

D:\wamp\www\laravel>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package jacopo/laravel-authentication-acl 1.0.0 could not be
 found.
  Problem 2
    - Conclusion: remove symfony/browser-kit v2.5.2
    - Conclusion: remove laravel/framework v4.2.7
    - Conclusion: don't install orchestra/testbench v2.2.1
    - Installation request for orchestra/testbench 2.2.\* -> satisfiable by orche
stra/testbench[v2.2.0, v2.2.1].
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install symfony/browser-kit v2.5.2
    - Conclusion: don't install laravel/framework v4.2.6
    - Installation request for behat/mink-goutte-driver \* -> satisfiable by beha
t/mink-goutte-driver[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.
0.7, v1.0.8, v1.0.9].
    - Conclusion: don't install symfony/browser-kit v2.5.1
    - orchestra/testbench v2.2.0 requires laravel/framework 4.2.\* -> satisfiable
 by laravel/framework[v4.2.7, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4
.2.6].
    - laravel/framework v4.2.5 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - laravel/framework v4.2.4 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - laravel/framework v4.2.3 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - laravel/framework v4.2.2 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - laravel/framework v4.2.1 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - laravel/framework v4.2.0 requires symfony/browser-kit 2.5.\* -> satisfiable
 by symfony/browser-kit[v2.5.2, v2.5.0, v2.5.1].
    - Conclusion: don't install symfony/browser-kit v2.5.0

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

D:\wamp\www\laravel>

**Comment by intrip** [comment]
You have to 
1) download laravel
2) update your _composer.json_ as following:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "laravel/framework": "4.2.*",
        "jacopo/laravel-authentication-acl": "1.1.*"
    },
    "autoload": {
        "classmap": [
            "app/commands",
            "app/controllers",
            "app/models",
            "app/database/migrations",
            "app/database/seeds",
            "app/tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable"
}
```

then run _composer update_
then run _php artisan authentication:prepare_
then run _php artisan authentication:install_

Now the package is installed.

**Comment by alirayaneh** [comment]
Thank you for reply I'll test it And I'll tell you

**Comment by alirayaneh** [comment]
thanx for all 
it install ed 
but when i will login in user page .. when pash login button redirected  to wite page,,
and when i will try to uplod a pic in admin page redirect ed to wite page 
and when i will try to get http://localhost/laravel/laravel/public/user/  this page rdirected to localhost/user
and when i will try to refresh capcha code pic .. re loaded all page .. 
and ...

**Comment by intrip** [comment]
Try to set `'debug' => true` option in file app/config/app.php. Then show me the error message.

**Comment by alirayaneh** [comment]
debug was true but no error massege showed..
when i will  try to login in user page rdircted to http://localhost/laravel/laravel/public/
and show laravel defult page(wite page with laravel logo)..
I've set 'url' => 'http://localhost/laravel/laravel/',
but Again rdircted  localhost/user when try to get   http://localhost/laravel/laravel/public/

**Comment by intrip** [comment]
Did you take a look at: https://github.com/intrip/laravel-authentication-acl/blob/master/docs/index.md#usage ?
Anyways you need to setup a virtualhost aswell for your laravel application take a look at http://laravel-recipes.com/recipes/25

**Comment by alirayaneh** [comment]
ok thanx a lot
