### ISSUE TITLE
this is not available for laravel 5.4

### ISSUE THREAD

**Issue by aliabdzad** [intrip/laravel-authentication-acl#155]
please make it usable with laravel 5.4 
thanks a lot ;)

**Comment by intrip** [comment]
I'll work on that

**Comment by intrip** [comment]
I don't have much time for that, a little donation would speed up the process if possible. Thanks everybody

**Comment by intrip** [comment]
@aliabdzad I've pushed a working version for Laravel 5.4 Waiting for your feedback
