### ISSUE TITLE
Problem when php artisan authentication:install

### ISSUE THREAD

**Issue by arcanoix** [intrip/laravel-authentication-acl#156]
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in C:\xampp\htdocs\l_acl\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 621

Why? :(

**Comment by jacopo-beschi-intersail** [comment]
You need to increase the max memory in your php_ini you can google that i think

**Comment by arcanoix** [comment]
Thanks!
