### ISSUE TITLE
composer and post-installation

### ISSUE THREAD

**Issue by icylace** [intrip/laravel-authentication-acl#16]
I would like to do the following in my composer.json:

``` js
"scripts": {
  "post-install-cmd": [
    ...
    "php artisan authentication:prepare",
    "php artisan authentication:install",
    ...
  ]
}
```

Is this a good idea ?

**Comment by intrip** [comment]
Yes, why not. That is for automatic default installation.
The only thing is that if you want to do some tuning after the prepare phase(for example use a custom db) you can't.

**Comment by icylace** [comment]
Oh, okay, good.

I was asking because [in the setup instructions](https://github.com/intrip/laravel-authentication-acl/blob/master/docs/index.md#setup) step 4 says "Now open the file app/config/app.php and add to the 'providers' option the following line: 'Jacopo\Authentication\AuthenticationServiceProvider'" and I wasn't sure if that was important to do before `php artisan authentication:prepare` and `php artisan authentication:install` which are steps 5 and 6 respectively.

**Comment by intrip** [comment]
Actually i forgot about that sorry. In order to run the command you need to register the service provider first in the config file sadly.

**Comment by icylace** [comment]
Oh, okay.
