### ISSUE TITLE
No stable version or backporting?

### ISSUE THREAD

**Issue by ghost** [intrip/laravel-authentication-acl#164]
[readme.md](/intrip/laravel-authentication-acl/blob/1.4/readme.md) says:

> for Laravel 5.3 use the version 1.3.*, for Laravel 5.2 use the version 1.3.15, for Laravel 5.1/5.0 use the version 1.3.11.

Now, I know that Laravel 5.2, 5.1, and 5.0 are deprecated, but even so, some websites (e.g. intranets) do use them.

It seems unlikely (based on the version numbers), but is there any plan to backport fixes to e.g. v1.3.15 or v1.3.11?

**Comment by intrip** [comment]
@sampablokuper I'm sorry but don't have enough time to keep up with this, but MRs are accepted, feel free to write any if you like.

**Comment by ghost** [comment]
No worries; I just wanted to be sure I understood. Thank you for confirming.
