### ISSUE TITLE
moloquent mongodb

### ISSUE THREAD

**Issue by ganapathi-threesquare** [intrip/laravel-authentication-acl#17]
Hi,
 i have to convert this admin panel to mongodb...how can i change mysql to mongodb

**Comment by intrip** [comment]
At the moment mongodb is not supported, sorry. 
But if you like to use mongodb with this package you have to do some tuning.
1) Use https://github.com/jenssegers/laravel-mongodb driver.
2) Rewrite the application repositories to work with mongodb: jacopo/laravel-authentication-acl/src/Jacopo/Authentication/Repository folder.

**Comment by ganapathi-threesquare** [comment]
If v change these things in mongo structure, is that whole admin panel wil work fine with MongoDB??

**Comment by ganapathi-threesquare** [comment]
what about schema's?? if v change the file mysql.sql, is that enough??

**Comment by ganapathi-threesquare** [comment]
hello i am waiting for your support.. can u do it asap pls??

**Comment by intrip** [comment]
Yes all data access belongs to that classes so if you change them the package you can work with mongodb.
And mongodb has no schema: http://www.mongodb.org/
Anyways as i said, sadly, mongodb is not supported so you should deal with this yourself. Have a nice day.

**Comment by ganapathi-threesquare** [comment]
Thanks dude.. For further queries, i just ping u.. Thank you

**Comment by intrip** [comment]
You're welcome.
