### ISSUE TITLE
error when i wont to get http://localhost/laravel/public/admin/users/profile/self

### ISSUE THREAD

**Issue by alirayaneh** [intrip/laravel-authentication-acl#18]
![error1](https://cloud.githubusercontent.com/assets/8302574/3792431/f60b7c5a-1b76-11e4-8be4-c08fca210605.jpg)

**Comment by intrip** [comment]
Did you install the package with authentication:prepare and authentication:install? Could you please send me the log file of the error. thanks

**Comment by alirayaneh** [comment]
hi ..
this is error log file 
http://s5.picofile.com/file/8133506234/laravel.log.html
or this
http://s5.picofile.com/d/bdc13926-fbf1-4603-a9f0-e2f9af9d3d7b/laravel.log

**Comment by icylace** [comment]
I'm also getting the same error and trying to figure it out.

I took a look at the line causing the error:

``` php
$custom_profile_repo = App::make('custom_profile_repository', $logged_user->user_profile()->first()->id);
```

within "vendor/jacopo/laravel-authentication-acl/src/controllers/UserController.php" in my Laravel project.

I used PHP's built-in [`get_class_methods()`](http://php.net/manual/en/function.get-class-methods.php) to discover that `first()` was not among the methods that `$logged_user->user_profile()` supported.

**EDIT**

I originally thought that [using `getResults()`](http://laravel.com/api/4.2/Illuminate/Database/Eloquent/Relations/HasMany.html#method_getResults):

``` php
$custom_profile_repo = App::make('custom_profile_repository', $logged_user->user_profile()->getResults()->first()->id);
```

would be a step in the right direction but I think I have a better idea of what is going on at least in my case...

When I register a new user and then login as that user I can see the profile page as expected.  However, the default admin account (admin@admin.com) **_does not_** have a profile page.

**Comment by intrip** [comment]
Yes, the problem should be that the default admin user (created with the install) doesn't have a profile record associated. I'll check that and fix the install script if that's the problem. 
Will do that later, i'll keep you updated.

**Comment by intrip** [comment]
It's fixed now. Run composer updated to download the fix.
To fix your live application you have to go on the user admin edit page, click on edit profile and then save an empty profile. At this point your admin user profile should be editable also from the top-right link in the panel.

**Comment by icylace** [comment]
Thanks !
