### ISSUE TITLE
signup CAPTCHA

### ISSUE THREAD

**Issue by icylace** [intrip/laravel-authentication-acl#19]
During account signup ("/user/signup") pressing the refresh CAPTCHA button refreshes the page and clears out the whole form.

It would be nice if either:
1. The CAPTCHA refresh does not cause a page refresh, or
2. The resulting page refresh does not clear out the first name, last name, and email address fields.

Also on the signup page the CAPTCHA verification does not seem to be working.  When I enter the CAPTCHA correctly the signup page will always reload with an error saying "The captcha is not valid, please try again."

**Comment by intrip** [comment]
I've in plan to have better captcha handing in future, about the bug you said i find it working on my version, did you try reloading the page and using the new captcha?

**Comment by icylace** [comment]
Yes, I tried manually reloading the signup page.  The issue remains.

BTW, I just checked my Laravel log.  Here's what I found:

```
[2014-08-05 22:17:26] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1049): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1017): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /Users/icylace/others/Repositories/ltc-cleaning/LTCTQ/public/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
```

**UPDATE**

Now I'm not so sure if the log error message I posted above is directly related to the CAPTCHA issue because I had similar messages come up for non-existent files that were being referenced from the site I'm working on.

**Comment by intrip** [comment]
Did you try to run composer update ?

**Comment by icylace** [comment]
Yes, I did a few minutes ago.  The issues remain.

**Comment by intrip** [comment]
Sorry for the problem, please try to clean your session and cookie, if doesn't still work try this:

temporary edit the file vendor/jacopo/laravel-authentication-acl/src/Jacopo/Authentication/Service/UserRegisterService.php at line 63 add :
`dd(\Session::get('authentication_captcha_value'), $input['captcha_text']);`
Then go on signup page and write the captcha you see and press register button.
Now compare the two captcha and tell me if they are equals.

**Comment by intrip** [comment]
I've also tried it on a fresh install and it works, please try to clean all your old data and try again. thanks.

**Comment by icylace** [comment]
Unfortunately, It's still not working but I haven't had the time to try a fresh install.  I'll try to do it next week.

**Comment by intrip** [comment]
Allright, keep me updated. If doesn't work still try to do the debug that i said to check for the input values.

**Comment by faithinna** [comment]
i tried the check they are equal so pls what  next
