### ISSUE TITLE
Incorrect Composer Package name

### ISSUE THREAD

**Issue by jameswagoner** [intrip/laravel-authentication-acl#2]
Packagist has your package listed as jacopo/laravel-authentication-acl

**Comment by intrip** [comment]
Yes "intrip" is my github account but the vendor name is "jacopo". I prefer to keep it like this for now.

**Comment by jameswagoner** [comment]
I understand that jacopo is the vendor name. Just pointing out a
discrepancy in your documentation.

Running composer update returned an error not finding the package. Looking
on Packagist lists it as jacopo/laravel-authentication-acl and not
jacopo/laravel-authentication as stated in your docs.

Once I added what is listed in Packagist, composer update ran successfully.

**Comment by intrip** [comment]
Oh, sorry i didn't see the typo. It's fixed now.
