### ISSUE TITLE
packages css issue

### ISSUE THREAD

**Issue by ganapathi-threesquare** [intrip/laravel-authentication-acl#20]
hi 
this is not loading public/pacakges/jacopo     all css not working..i dont know what is the problem i am using mac

**Comment by intrip** [comment]
Did you run all the setup commands? authentication:prepare and authentication:install?
What version are you using?

**Comment by robwent** [comment]
This happened to me but thought it was because I renamed public to pblic_html
I had to download the master and copy the files manually
