### ISSUE TITLE
group assignement on signup Enhancement

### ISSUE THREAD

**Issue by TolotraRam** [intrip/laravel-authentication-acl#23]
Hi,

Great work, just wonder what can i do if i want that all new user will be in a group on their signup?

Thank you

**Comment by intrip** [comment]
I'll add an event so that you can hook on it. Will do it soon. I'll keep you updated.

**Comment by intrip** [comment]
I've pushed on master the fix that throws two events: "service.registering" before registering a new user, "service.registered" after registering a new user. 
You can listen on them and do what you like. To try that put "dev-master" on your composer.json and run "composer update".
I'll add that feature in the next stable release aswell, but for now you need to use the master branch.
Waiting for your feedback.

**Comment by TolotraRam** [comment]
Thank you so much, i wanna try it now and give a feedback anyway i should try it on a fresh install of laravel coz i hardcoded your package's view to fit my need, it will be welcomed if you feed the documentation on how to override the views.

**Comment by intrip** [comment]
Composer update will not override your changes to the view, anyways you could back up your file before running that for safety.
Considering the doc i've a plan for that.

**Comment by intrip** [comment]
I've pushed a new tag with a lot of new event hooks. Please update your version and check them out on the docs. https://github.com/intrip/laravel-authentication-acl/blob/master/docs/index.md#events

**Comment by TolotraRam** [comment]
hi,
already updated and all event i tested worked fine but in the "service_registered" event i need the last inserted id to assign it to a group and i don't know what is the best way to do it. Any help will be welcomed.

**Comment by intrip** [comment]
Right, i've added the user created to the event(and updated the docs), so you can use $user->id. Just retagged now. Run composer update in few minutes to get the latest version.

**Comment by intrip** [comment]
Just to be sure delete vendor/jacopo folder before running composer update.

**Comment by TolotraRam** [comment]
Well done, great job @intrip 
Thank you very much.

**Comment by intrip** [comment]
You're welcome. Closing the issue right now.
