### ISSUE TITLE
How do the premissions work

### ISSUE THREAD

**Issue by Swiek** [intrip/laravel-authentication-acl#24]
Hi,

Playing around with your authentication class and i was wondering the following.
The permissions work like this:

_permission-editor
_profile-editor
_group-editor
_user-editor

What's the reference with the controllers and the actions you can do in the controller?
For example what if we take the default HomeController.php with the showWelcome action. How can i add the as a premission which i can assign to a user?

Maybe a basic question but just switching from CI to Laravel.

Kind regards,

Erwin

**Comment by intrip** [comment]
If you want to show a route only to users with certain permissions you need to use the "has_permission" filter, check the docs here for more info: https://github.com/intrip/laravel-authentication-acl/blob/master/docs/index.md#howto

**Comment by Swiek** [comment]
I see, I think i missed that part for some reason or didn't see the link of the 'before' => 'has_perm:_permissionA,_permissionB' that these are the permission you create in the admin.

If i am going to extend the admin with new functions, i guess it's bad practice to do this in the system you created? What's the best way to extend your system with new frontend and backend options. without losing the ability to update your system to the latest version? Should i just use the app/controller folder and the app/routes.php file?

**Comment by intrip** [comment]
About the views, you can override my views but replacing the views in "app/views/package/jacopo/laravel-authentication-acl" and you won't have any problem with most of the updates.
For the rest you can add you own routes in your application just don't touch the vendor folder. I'm also adding some more events that allow you to hook in the core events in next relase.
