### ISSUE TITLE
User sign

### ISSUE THREAD

**Issue by TolotraRam** [intrip/laravel-authentication-acl#25]
Hi,

I don't understand why user with no permission can access admin dashboard but with less menu, is it not better to create a user dashboard on frontend to handle this, and all action related to user can be accomplished there? may be i'm wrong but can you afford some explanation about this.

Thanks

**Comment by intrip** [comment]
There are two logins: the admin/login and the user/login, the user login is the login for the users and they are being redirected to a custom page after login, there you can show them what you like.
the admin login is intended only for people that want an admin panel and incase the don't have any permission they basically don't see anything besides dashboard, anyways the menu in admin area are customizable via the menu.php config file.

**Comment by TolotraRam** [comment]
i really agree anyway i do this step :
- user/signup 
- after confirmation i go to user/login and i 'm redirected to a custom route but if i access admin/dashboard without login out the last user so i get into it but with less menu.

My question is that is there a way to restrict all route related to admin for non-admin user ? or i miss something.

**Comment by intrip** [comment]
You can add _superadmin permission to the dashboard like this:

```
    "list" => [
            [
                    "name"        => "Dashboard",
                    "route"       => "dashboard",
                    "link"        => URL::route('dashboard.default'),
                    "permissions" => ["_superadmin"]
            ],
```

on menu.php configuration file

**Comment by TolotraRam** [comment]
:+1:  Thank you.
