### ISSUE TITLE
/login does nothing?

### ISSUE THREAD

**Issue by broakenmedia** [intrip/laravel-authentication-acl#26]
I just get  'was not found on this server.'

everything installed correctly? Got the tables created, the files are all there, but nothing works?

**Comment by intrip** [comment]
Did you setup you virtual host? http://laravel.com/docs/quick

**Comment by broakenmedia** [comment]
I can access the 'You have arrived' page if that helps? looking at that page now
On 22/08/2014 20:02:50, jacopo notifications@github.com wrote:
Did you setup you virtual host? http://laravel.com/docs/quick [http://laravel.com/docs/quick]
&mdash;

**Comment by intrip** [comment]
doest /login is the only link that doesn't work? for example admin/login works? try to type php artisan routes too see if they are registered

**Comment by broakenmedia** [comment]
http://share.joescott.me/b8c7.png

seem to be! none of the links work!

**Comment by intrip** [comment]
Could you please post me the full error message? You have write permission in app/storage folder?

**Comment by broakenmedia** [comment]
http://share.joescott.me/552632.png

**Comment by broakenmedia** [comment]
neater version ^ and yes i do, getting message now

**Comment by broakenmedia** [comment]
The requested URL /admin/public/login was not found on this server.

(admin is the name of the laravel install folder)

**Comment by intrip** [comment]
The problem is that the link is /admin/login. You need to setup your virtual host. Here is an example: 
http://laravel-recipes.com/recipes/25

**Comment by broakenmedia** [comment]
That's exactly what i have, /admin/public, works fine?

**Comment by broakenmedia** [comment]
```
<VirtualHost *:80>
  # Admin email, Server Name (domain name), and any aliases
 ServerAdmin Joe@BroakenMedia.co.uk
 ServerName socialfriendfinder.co.uk
 ServerAlias www.socialfriendfinder.co.uk

 # Index file and Document Root (where the public files are located)
 DirectoryIndex index.html index.php
 DocumentRoot /home/xbroak/public/socialfriendfinder.co.uk/public_html/

 # Log file locations
 LogLevel warn
 ErrorLog /home/xbroak/public/socialfriendfinder.co.uk/logs/error.log 
 CustomLog /home/xbroak/public/socialfriendfinder.co.uk/logs/access.log combined

<IfModule mod_fastcgi.c>
            AddHandler php5-fcgi .php
            Action php5-fcgi /php5-fcgi
            Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
            FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -host 127.0.0.1:9000 -pass-header    Authorization
    </IfModule>

</VirtualHost>
```

**Comment by broakenmedia** [comment]
In the folder BEFORE admin, i have a normal static page site, i then want to make the admin panel in laravel, i,e, /admin - Forgive me if i'm missing this entirely

**Comment by broakenmedia** [comment]
Shall i give up? :P

**Comment by intrip** [comment]
The fact is that Laravel uses Front controller pattern. So your document root folder should be the public laravev folder, for all you other static page what you have to do is the following:
1) copy all of them in the app/views folder
2) make a route for every of em such this:

```
Route::get('url', function(){
   return View::make('static.page.php');
});
```

**Comment by broakenmedia** [comment]
So i should aim for it to be simply /public/X for everything?

**Comment by broakenmedia** [comment]
i just made a seperate virtual host for admin.mysite.co.uk
made laravel the root, again, accessing admin.mysite.co.uk/public works
/public/login does not, am i missing something? because as far as i can tell laravel requires the use of /public/

**Comment by intrip** [comment]
no, the fact is that you should have /public as document root so you don't have to type public in the url for your routes. You shoul acces it as /login ant not /public/login otherwise only the / route will work correctly.

**Comment by broakenmedia** [comment]
oh! ok, makes sense, HOWEVER 

DocumentRoot /home/xbroak/public/admin/public

having done that, and now being able to access the homepage view just the domain, i STILL cant find login.

**Comment by intrip** [comment]
if your laravel folder(the one that contains app folder is xbroak then your document root should be xbroak/public. at this point it should work, for the static page then make your own route that returns view::make

**Comment by broakenmedia** [comment]
the laravel folder is in the root directory of the new site (admin) the other folders are just the path to my sites directory

**Comment by intrip** [comment]
Ok then you need to restart apache and it should work

**Comment by broakenmedia** [comment]
that's exactly what i've done! 

http://share.joescott.me/84fc9.png

(that url wont work for you, using hosts file for now)

**Comment by intrip** [comment]
This is my configuration:

```
<VirtualHost *:80>
  DocumentRoot /Library/WebServer/Documents/authentication/public
  ServerName local.authentication
  SetEnv environment local
</VirtualHost>
```

Then i added to /etc/hosts:

```
127.0.0.1 local.authentication
```

And it works for me, you could try like that. Using macosx maverick + apache here

**Comment by intrip** [comment]
forgot my link are like this:http://local.authentication/admin/login

**Comment by broakenmedia** [comment]
Im on a live server, but i see no difference in our configs :L

Quick question, when i moved the files to this new sites base directory, i just copied them from the original setup folder, do i need to start fresh or do they not mind what folder they're in?

**Comment by intrip** [comment]
Better to start fresh. Since your problem is laravel-related(doesn't belong to this package) you can try to ask on laravel irc forum and you'll be helped for sure.

**Comment by broakenmedia** [comment]
Well, sorry for the delay, i Rm \* 'd my entire server, woops.

Started fresh, correct laravel, in the root, installed as per the github instructions, all passed.

Still nothing, no login, only, 'You have arrived'

**Comment by intrip** [comment]
I think you're problem is still related in some mistake in laravel installation, please try this tutorial and everything should be working:
http://wiki.laravel.io/A_Beginner's_Guide_to_Laravel_4. Remember to create custom routes for your static views

**Comment by broakenmedia** [comment]
Thats exactly what i followed D:

I think i'm going to just have to make the panel myself from scratch at this point, it all works except for ACL :(

**Comment by intrip** [comment]
I think you have some problem with laravel virtualhost configuration still. Maybye try to run composer update.

**Comment by vinizinmoraes** [comment]
+1 I am getting the same problem, my virtualhost is fine i can access the "You have arrived" through my dev url, but if i add "/login", doesn't work. I am using windows. I am using Laravel 4.2.

**Comment by vinizinmoraes** [comment]
I solved my problem. My rewrite_module was not enabled :disappointed_relieved:

**Comment by broakenmedia** [comment]
What command? Mine seems to be enabled and i'm using 'AllowOveride all' in the virtual host

Kind regards

Joe scott
Lead developer and founder |
BroakenMedia | 
@BroakMedia

**Comment by broakenmedia** [comment]
Solved! Vinizin, good stuff!

For anyone with the same issue:

ENABLE MOD_REWRITE - On Your SSH Console
1: sudo a2enmod rewrite
2: service apache2 reload

if your given an error (Command not found) [I did :-1: ]
1: sudo a2enmod userdir
2: service apache2 reload
3: sudo a2enmod rewrite
4: service apache2 reload
