### ISSUE TITLE
Call to a member function beginTransaction() on a non-object

### ISSUE THREAD

**Issue by ganapathi-threesquare** [intrip/laravel-authentication-acl#27]
When i am creating user showing this errror???
- Drivers that doesn't support foreign keys check
  - @var array
    */
    public static $no_foreign_keys_drivers = ['sqlite', 'pgsql'];
  
  public static function startTransaction()
  {
      static::getConnection()->getPdo()->beginTransaction();
      static::stopForeignKeysCheck();
  }

**Comment by intrip** [comment]
Sorry, what is the error message? What dbms are you using?

**Comment by ganapathi-threesquare** [comment]
with mongodb

**Comment by intrip** [comment]
MongoDB is currently not supported, supported DBMS are: mysql, postgres and sqlite.
I'll add this support in next releases but not soon.
