### ISSUE TITLE
rest token enhancement

### ISSUE THREAD

**Issue by bingalls** [intrip/laravel-authentication-acl#29]
Jacopo: nice work!
I'd like to see your authorization system integrated with laravel-auth-token https://github.com/tappleby/laravel-auth-token for ReST support.
The next version is working on JWT support, which is part of the OpenID Connect standard, and plays well with OAuth 2.

There are some Open Source dashboards in JavaScript, if & when you get to that point.

**Comment by intrip** [comment]
Allright i'll take a look when i can.

**Comment by simontech** [comment]
I'm interested in REST auth functionality also.  I'm currently working to implement myself but I don't want to reinvent the wheel.  Would be glad to contribute if there's a start in progress (v1.2?).  Thanks for all the hard work so far Jacopo.

**Comment by bingalls** [comment]
I ended up using https://github.com/tymondesigns/jwt-auth (Larvel based) which is simpler than laravel-auth-token.
The author of jwt-auth is updating docs. Part of these upcoming docs should include a routes.php and/or filter.php, that are in the architecture of laravel-auth-token & laravel-authentication-acl.

One stumbling block, is that my SPA front-end server runs LiveReload.js, and loses the token after each restart, which slows development & debuggng. Consider adding a debug mode.

**Comment by intrip** [comment]
My first plan for version 1.2 is to complete the acceptance test suite, then i think i can work some new feature like implementing a REST api for login/logout. If you have any ideas to share with me please write me a PR. thanks.

**Comment by intrip** [comment]
Not planning that for now.
