### ISSUE TITLE
Have permissions on a route that is not in menu?

### ISSUE THREAD

**Issue by andreas22** [intrip/laravel-authentication-acl#3]
Hi,

Regards to permissions, how I can set permissions to a route that is not shown inside the admin menu? For example I have a controller which has different actions like list, edit & delete. I want a superadmin to access all but a normal user to have permissions to access only the list action only.

**Comment by intrip** [comment]
You could create a filter that deny the access to the route you don't have a given permission:

``` php
Route::filter('can_see_perm_name', function()
{
    $permission = '_perm_name';
    $auth_helper = App::make('authentication_helper');
    if(! ($auth_helper->hasPermission( $perm )))  App::abort('401');
});
```

And then put this code in a filter.php file and include it in your bootstrap/start.php file.
Then use this filter as a 'before' filter in the route where you need it. 
There is some documentation on Laravel4 filter [here](http://laravel.com/docs/routing#route-filters)
Otherwise you could just put the code in the callback at the start of the action associated to your route. 
Anyways i'm planning to add this functionality soon using a configuration file.
If you have any other problem feel free to ask me.

**Comment by andreas22** [comment]
By adding a second filter will overwrite the previous one. For example, if I have a user which is superadmin, filter 'can_see' will pass but my new filter will deny access as the user will not have the exact permission in his list.

**Comment by andreas22** [comment]
I have a suggestion, if you modify the below function to return the route name as shown below then it will be able to add permissions directly on a route in permissions pave just by adding the route name.

public function getPermFromRoute($route)
    {
        $menu_info = Config::get($this->config_path);

```
    foreach ($menu_info as $menu)
    {
        if($menu[$this->route_variable_index] == $route)
            return $menu[$this->pemissions_variable_index];
    }

    return Route::currentRouteName();
}
```

**Comment by intrip** [comment]
I'll create a fix for this problem so that if you don't write the  menu "name" in the configuration file it will handle permission with the filter "can_see" but doesn't show the route in the menu.

**Comment by andreas22** [comment]
nice, great job keep up the good work :)

**Comment by intrip** [comment]
I've added that and pushed it in the version 1.1.2. Please try it and let me know if you find any problem. Now if you don't want to show the item in the menu just leave the "name" field (in config file) blank.

**Comment by andreas22** [comment]
it would be nice all this information to be inside the documentation as well in more detail :)

**Comment by intrip** [comment]
Yes, i'll try to do that when i can, but i'd be happy if you could help me with the docs and write a pull request for that so i can just merge it with the repo. Thanks for help :)

**Comment by andreas22** [comment]
ok let me see what i can do

**Comment by intrip** [comment]
Thanks for help, really appreciate it. You will be on contributors list on github :+1:
