### ISSUE TITLE
user_profile method not defined!

### ISSUE THREAD

**Issue by letian1225** [intrip/laravel-authentication-acl#31]
can't install! After I changed a row in SentryUserRepository.php, 
# 

  //$user = $this->sentry->createUser($data);
            $user = $this->model->create($data);
# 

passed install. But now can't login to admin/login page. Always appear user_profile not defined exception. The code need use the subclass user to use the user_profile  method,  but I don't know how to solve it now.
# 

Next exception 'ErrorException' with message 'Call to undefined method Illuminate\Database\Query\Builder::user_profile() (View: /srv/www/exampletest.com/vendor/jacopo/laravel-authentication-acl/src/views/admin/layouts/partials/avatar.blade.php) (View: /srv/www/exampletest.com/vendor/jacopo/laravel-authentication-acl/src/views/admin/layouts/partials/avatar.blade.php) (View: /srv/www/exampletest.com/vendor/jacopo/laravel-authentication-acl/src/views/admin/layouts/partials/avatar.blade.php) (View: /srv/www/exampletest.com/vendor/jacopo/laravel-authentication-acl/src/views/admin/layouts/partials/avatar.blade.php) (View: /srv/www/exampletest.com/vendor/jacopo/laravel-authentication-acl/src/views/admin/layouts/partials/avatar.blade.php)' in /srv/www/exampletest.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2113

**Comment by intrip** [comment]
try to remove vendor/jacopo folder, run composer update and install again. Tell me if it's fixed.

**Comment by letian1225** [comment]
Thanks for your reply, I am trying your suggestion.

**Comment by letian1225** [comment]
Hi, intrip, I just installed again, but the problem remains.

**Comment by letian1225** [comment]
The install process can't pass, the error messages:
[BadMethodCallException]
  Call to undefined method Illuminate\Database\Query\Builder::user_profile()

**Comment by intrip** [comment]
Could you post me the full error stack? Did you change something in the vendor folder? Which version of php and of the package you have installed?

**Comment by intrip** [comment]
Please tell me php version and package version and the full error stack so i can try to reproduce the error.

**Comment by letian1225** [comment]
php: PHP 5.5.14
and your package version: 1.2, the latest.
Before the 1.2 version, I tried 1.1, but failed. So I tried 1.2 afterwards.

**Comment by letian1225** [comment]
The complete display:

---
-     Application In Production!     *
  **************************************

Do you really wish to run this command? y
Migration table created successfully.
Migrated: 2014_02_19_095545_create_users_table
Migrated: 2014_02_19_095623_create_user_groups_table
Migrated: 2014_02_19_095637_create_groups_table
Migrated: 2014_02_19_095645_create_user_throttle_table
Migrated: 2014_02_19_160516_create_permission_table
Migrated: 2014_02_26_165011_create_user_profile_table
Migrated: 2014_05_06_122145_create_profile_field_types
Migrated: 2014_05_06_122155_create_profile_field

  [BadMethodCallException]
  Call to undefined method Illuminate\Database\Query\Builder::user_profile()

authentication:install

**Comment by letian1225** [comment]
And I absolutely never changed the vendor package.

**Comment by intrip** [comment]
Ok 1.2 is still unstable please use the 1.1. I'll take a look at the error.

**Comment by letian1225** [comment]
I justed noticed the 1.2 version justed changed a few lines.
So I tried it. Now I tested 1.1 again, the same error message appears.
I have reviewed the code a whole day, I think the code should use the User class in jacopo package, not the sentry class in the sentry package, otherwise user class instance(super class) can't see the user_profile method(in your User subclass) in your code. Just as a reference. Look forward to use your 
code in my project, thanks.

**Comment by intrip** [comment]
I've just installed everything with php 5.4 and runs smoothly.
The change you made in SentryUserRepository is not correct. This repository is based on sentry user model class. So that change wont make the software breakage.

**Comment by ryanrobertsname** [comment]
I ran across this same issue, I believe the issue was that the config file for Sentry was specifying that the Sentry User model be used.

This package publishes a sentry config file that specifies it's own User model to be used (look in config/packages/jacopo/laravel-authentication-acl/sentry)

In my case I was messing around with some other Sentry packages and must of got some lines crossed somewhere.... If you run across this issue check out the mentioned config file.
