### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by ylynfatt** [intrip/laravel-authentication-acl#32]
Is there a way to integrate this with LDAP?

**Comment by intrip** [comment]
This package leverage Cartalyst/Sentry for authentication, and it doesn't support ldap natively. Anyways I saw this fork or sentry that support ldap login: https://github.com/anndro/SentryLdap. 
So it's possible to integrate it with ldap but for now i don't have the time to do that. If you like you can make a pr and the community will be happy :+1:

**Comment by ylynfatt** [comment]
Thanks, I'll give SentryLdap a try first.

**Comment by intrip** [comment]
Don't have time for that sorry
