### ISSUE TITLE
Email subject translation

### ISSUE THREAD

**Issue by aescarcha** [intrip/laravel-authentication-acl#34]
First of all, great work! Your package saved me a lot of time.

Now my doubt, I need to translate the mail subjects, is there any way to do this?

Thanks

**Comment by intrip** [comment]
You made a nice point, i didn't handle translation yet in this package anyways i can put all mail subject in a configuration file so you can easily change them. Will do that in version 1.2 (not stable yet tho). I'll keep you updated.

**Comment by aescarcha** [comment]
That'd be great, thanks :)

**Comment by intrip** [comment]
I've just pushed that in version 1.2.1 please check that and tell me if you find any problems.

**Comment by aescarcha** [comment]
It works nicely thanks, I'll test it further in my app and tell you if anything fails.

**Comment by intrip** [comment]
Lovely, keep me updated and be aware 1.2 is still the develop branch :smile:  .

**Comment by intrip** [comment]
I've pushed that change into branch 1.2 Also pushed the flash messages translation
