### ISSUE TITLE
Bug: when deleting a permission from a user, wrong permission is deleted!

### ISSUE THREAD

**Issue by andreas22** [intrip/laravel-authentication-acl#4]
Example: I have a user with 3 permissions and they are shown in the following order:
1. superadmin
2. editor
3. reader

If I delete either superadmin or editor, reader will be deleted instead. Always the last permission is remove instead of the selected one.

**Comment by intrip** [comment]
Allright, i'll take a look and let you know when i'm done

**Comment by andreas22** [comment]
The problem is that if a user has multiple permissions every time the delete button is clicked it submits $('.form-del-perm').submit(); and as a result it picks the latest permission.

Suggestion:
1. Inside each delete form parameters add the following:

'id' => 'frm' . $permission->id
1. add attribute to span called ss-perm-id

<span class="input-group-addon form-button button-del-perm" ss-perm-id="{{ $permission->id }}">
<span class="glyphicon glyphicon-minus-sign add-input"></span>
</span>
1. and update the click event of delete button as follows:

$(".button-del-perm").click( function(){
        var permission_id = $(this).attr('ss-perm-id');
        $('#frm'+permission_id).submit();
    });

**Comment by intrip** [comment]
I've fixed that and uploaded a new tag: 1.1.2. Please try that and let me know if you find any problem.
