### ISSUE TITLE
Overriding views

### ISSUE THREAD

**Issue by TolotraRam** [intrip/laravel-authentication-acl#41]
Hi,
I've override the views to suit my needs and last time i update nothing change but now after a composer update all my change disappear and i get the basic design.
My question is that is there a proper way to override jacopo package such as views, controller, menu and so?

**Comment by intrip** [comment]
Did you take a look at https://github.com/intrip/laravel-authentication-acl/blob/1.1/docs/index.md#howto?
If you do that and chenge the app/views/packages/jacopo views you shouldn't have that problem.

**Comment by TolotraRam** [comment]
Ah, sorry last time i check the doc there's nothing about the custom view, so i 've override the view in the package vendor. Think it will be good right now.
Thanks again ! i will close this right now.
