### ISSUE TITLE
Class 'Jacopo\Authentication\Controllers\Config' not found

### ISSUE THREAD

**Issue by astormcupdx** [intrip/laravel-authentication-acl#42]
Using (what I think is?) the latest stable release

```
    "jacopo/laravel-authentication-acl": "1.2.2"    
```

I'm getting the following error when I try to edit a group

> Class 'Jacopo\Authentication\Controllers\Config' not found

Steps to Reproduce
1. Login into the back-end with the default admin@admin.com super user
2. Click on Groups
3. Click the "Edit Icon" next to 'superadmin'
4. Click the Blue "Save" button

Expected Behavior: Group information saves and redirects properly

Actual Behavior: Laravel error page displays

Whoops screenshot attached below

![screenclip](https://cloud.githubusercontent.com/assets/8497168/4708843/eccd621e-589a-11e4-995e-db13af4ba2b8.png)

**Comment by intrip** [comment]
Sorry this is not the latest stable i'm putting in some new stuff. the latest stable is 1.1.\* Anyways i'll fix that problem

**Comment by intrip** [comment]
Anyways it's fixed also on 1.2 branch now
