### ISSUE TITLE
Can't assign group or permissions to new user?

### ISSUE THREAD

**Issue by MaggieCabrera** [intrip/laravel-authentication-acl#43]
I make a new user on the dashboard, new permissions and new group, but when I try to assign the group or permissions to the user, it will not apply. No error message given, it just reloads the edit page and no changes are applied.

**Comment by intrip** [comment]
Which version are you using? Could you post me a screenshoot ?

**Comment by MaggieCabrera** [comment]
I'm using dev-master. Maybe I'm not understanding how this works. When I go to the users list and search by groups, my new users won't show up (cause they have no group assigned)

http://i.imgur.com/dGOP8uU.png

**Comment by intrip** [comment]
Don't use dev-master. It's not updated just use 1.1.\* check here: https://github.com/intrip/laravel-authentication-acl/blob/1.1/docs/index.md#setup Remember to run composer update.
Try that and tell me if the issue still persist.

**Comment by MaggieCabrera** [comment]
I did so because I saw on the packagist, I just changed the version, but it still doesn't work (I did composer update). I haven't made any more changes, the project has just started out, only created two users to test.

**Comment by intrip** [comment]
I'll take a look at that.

**Comment by intrip** [comment]
I've tried that and works for me, to add a group you clicked on the plus button? after that you should see the new group/permission under the select with a minus button at the left.

**Comment by MaggieCabrera** [comment]
Yeah, I obviously didn't understand how it worked, I was simply selecting the group/permission, sorry for wasting your time and thanks for explaining it :)
