### ISSUE TITLE
Issue with login not remembering user

### ISSUE THREAD

**Issue by MaggieCabrera** [intrip/laravel-authentication-acl#44]
This issue is probably something related to the config of my preprod server, cause I don't have it in my local environment, but since I don't know how this is handled I wanted to ask for help.

I have the admin user that you created and I login to my application. Either in the login dashboard or the regular user side of the page, if I navigate a bit (maybe go to admin panel, try to create a new group or set of permissions) I get prompted with the login again, like I've been forced to logout. 

As I said this isn't happening to me in local, what can be causing this?

**Comment by intrip** [comment]
That should be a session related problem. You enabled cookie on the browser? Does the server have a max_session duration in php.ini?

**Comment by MaggieCabrera** [comment]
Mmmh, the server was setup for me, I didn't handle it directly but I saw it has hhvm on it and I see this in php.ini: session.gc_maxlifetime = 1440 could that be the issue?

**Comment by intrip** [comment]
Yes you need to increment that.

**Comment by MaggieCabrera** [comment]
mmh, 1440 seconds would be 24 minutes and it's happening to me much faster than that, maybe every minute or less

**Comment by intrip** [comment]
You could still try to increment that and see it's either a session or cookie problem anyway.

**Comment by MaggieCabrera** [comment]
You are probably right, I'll talk to the sysadmin to handle that, thank you!

**Comment by intrip** [comment]
You're welcome. Waiting for your feedback

**Comment by MaggieCabrera** [comment]
Much better now, thanks, that fixed it apparently
