### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by mpemberton5** [intrip/laravel-authentication-acl#47]
Thoughts on creating a version to work with Laravel 5?

**Comment by intrip** [comment]
I will make that working with laravel 5 (the 1.2 branch) soon.

**Comment by mpemberton5** [comment]
Awesome!  Thanks for the reply!

**Comment by intrip** [comment]
I'm thinking to write a new branch for the laravel 5 version i'll keep you updated.

**Comment by mpemberton5** [comment]
It would make a ton of sense to separate laravel 4 and laravel 5 builds.
So you are on the right track!
