### ISSUE TITLE
Sqlite Table Doesn't Exist Issue

### ISSUE THREAD

**Issue by ryanrobertsname** [intrip/laravel-authentication-acl#49]
When running tests not related to this application using sqlite in memory, I'm getting table doesn't exist errors.  This didn't exist before adding this package.

Found that this line in the service provider is causing the issue:  $this->app['validation.presence']->setConnection('authentication');

I'm not entirely sure why the connection is being explicitly set on the presence validator.  Commenting out the line makes the tests work and the application SEEMS to function alright.

Any ideas on what's happening with this?

Great work on this package by the way! Thanks...

**Comment by intrip** [comment]
The problem is that for testing it overrides the laravel database presence validator connection to use the memory one. I'll take a look in order to fix that problem. Anyways that line is only for testing purpose so it's fine.
