### ISSUE TITLE
Allowing users to create groups

### ISSUE THREAD

**Issue by rbruhn** [intrip/laravel-authentication-acl#50]
Currently, I'm using Sentry for my users and groups. I like your interface but I need the ability for users to create/edit/delete their own groups (outside of the admin area). In my system, Groups manage Projects and project permissions are set by the over all Group permission.

Is there a way to modify things so a Group can be Owned by a user?
Also, is it possible to extend your user and group model so custom methods can be written?

Thanks

**Comment by intrip** [comment]
You need to write your own code that does that but it's completely possible, you can just copy&paste the code in the GroupsController and make your own implementation for the user/side.

**Comment by rbruhn** [comment]
Thanks. I ended up simply looking at your css and views, integrating the look with my existing system.

**Comment by intrip** [comment]
You're welcome

Best
Jacopo

Il 31/10/14 16:37, rbruhn ha scritto:

> Thanks. I ended up simply looking at your css and views, integrating 
> the look with my existing system.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/intrip/laravel-authentication-acl/issues/50#issuecomment-61278914.

## 

Jacopo Beschi Cell. (+39) 3406192148 Skype: lasttry_1234 Twitter: 
https://twitter.com/JacopoBeschi
