### ISSUE TITLE
php artisan migrate:refresh failed

### ISSUE THREAD

**Issue by gan068** [intrip/laravel-authentication-acl#58]
Laravel 4.2

jacopo/laravel-authentication-acl version 1.2.*

$ php artisan migrate:refresh

```
PHP Fatal error:  Class 'CreateProfileField' not found in /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 301
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/abc.com.tw/artisan:0
PHP   2. Symfony\Component\Console\Application->run() /home/vagrant/Code/abc.com.tw/artisan:59
PHP   3. Symfony\Component\Console\Application->doRun() /home/vagrant/Code/abc.com.tw/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/Code/abc.com.tw/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   5. Illuminate\Console\Command->run() /home/vagrant/Code/abc.com.tw/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   6. Symfony\Component\Console\Command\Command->run() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
PHP   7. Illuminate\Console\Command->execute() /home/vagrant/Code/abc.com.tw/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Illuminate\Database\Console\Migrations\RefreshCommand->fire() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Console/Command.php:112
PHP   9. Illuminate\Console\Command->call() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:40
PHP  10. Illuminate\Console\Command->run() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Console/Command.php:128
PHP  11. Symfony\Component\Console\Command\Command->run() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
PHP  12. Illuminate\Console\Command->execute() /home/vagrant/Code/abc.com.tw/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP  13. Illuminate\Database\Console\Migrations\ResetCommand->fire() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Console/Command.php:112
PHP  14. Illuminate\Database\Migrations\Migrator->rollback() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:61
PHP  15. Illuminate\Database\Migrations\Migrator->runDown() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:172
PHP  16. Illuminate\Database\Migrations\Migrator->resolve() /home/vagrant/Code/abc.com.tw/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:192
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'CreateProfileField' not found","file":"\/home\/vagrant\/Code\/abc.com.tw\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Migrations\/Migrator.php","line":301}}
```

**Comment by Yolcar** [comment]
I have the same problem

**Comment by intrip** [comment]
i'll take a look

**Comment by mserralta** [comment]
Same here

**Comment by faithinna** [comment]
WHEN I LOG IN FROM ADMIN/LOGIN  PAGE I GET THIS ERROR

ErrorException (E_UNKNOWN) 
Call to undefined method Illuminate\Database\Query\Builder::user_profile() (View: C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php) (View: C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php) (View: C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php) (View: C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php) (View: C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)

**Comment by intrip** [comment]
I've pushed a fix to version 1.2.7 please run composer update and let me know if the problem persist.

**Comment by faithinna** [comment]
still getting the same error

ErrorException (E_UNKNOWN)  ErrorException thrown with message "Call to
undefined method Illuminate\Database\Query\Builder::user_profile() (View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)"
Stacktrace: #60 ErrorException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#59 Illuminate\View\Engines\CompilerEngine:handleViewException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:41
#58 ErrorException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#57 Illuminate\View\Engines\CompilerEngine:handleViewException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:41
#56 ErrorException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#55 Illuminate\View\Engines\CompilerEngine:handleViewException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:41
#54 ErrorException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#53 Illuminate\View\Engines\CompilerEngine:handleViewException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:41
#52 ErrorException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#51 Illuminate\View\Engines\CompilerEngine:handleViewException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:41
#50 BadMethodCallException in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:2063
#49 Illuminate\Database\Query\Builder:__call in <#unknown>:0 #48
Illuminate\Database\Query\Builder:user_profile in <#unknown>:0 #47
call_user_func_array in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:914
#46 Illuminate\Database\Eloquent\Builder:__call in <#unknown>:0 #45
Illuminate\Database\Eloquent\Builder:user_profile in <#unknown>:0 #44
call_user_func_array in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:2962
#43 Illuminate\Database\Eloquent\Model:__call in
C:\xampp\htdocs\medifile_new\project\app\storage\views\3a13028d17d20eec4cb670b8ff79fb77:1
#42 Cartalyst\Sentry\Users\Eloquent\User:user_profile in
C:\xampp\htdocs\medifile_new\project\app\storage\views\3a13028d17d20eec4cb670b8ff79fb77:1
#41 include in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:37
#40 Illuminate\View\Engines\PhpEngine:evaluatePath in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:56
#39 Illuminate\View\Engines\CompilerEngine:get in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:134
#38 Illuminate\View\View:getContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:102
#37 Illuminate\View\View:renderContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:76
#36 Illuminate\View\View:render in
C:\xampp\htdocs\medifile_new\project\app\storage\views\cd5ab7c8e550d13836fe51cce5a09735:23
#35 include in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:37
#34 Illuminate\View\Engines\PhpEngine:evaluatePath in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:56
#33 Illuminate\View\Engines\CompilerEngine:get in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:134
#32 Illuminate\View\View:getContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:102
#31 Illuminate\View\View:renderContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:76
#30 Illuminate\View\View:render in
C:\xampp\htdocs\medifile_new\project\app\storage\views\020c5193fe73bf852983843ca6552508:31
#29 include in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:37
#28 Illuminate\View\Engines\PhpEngine:evaluatePath in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:56
#27 Illuminate\View\Engines\CompilerEngine:get in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:134
#26 Illuminate\View\View:getContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:102
#25 Illuminate\View\View:renderContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:76
#24 Illuminate\View\View:render in
C:\xampp\htdocs\medifile_new\project\app\storage\views\100fa670910a33ce696e784a9872d989:11
#23 include in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:37
#22 Illuminate\View\Engines\PhpEngine:evaluatePath in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:56
#21 Illuminate\View\Engines\CompilerEngine:get in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:134
#20 Illuminate\View\View:getContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:102
#19 Illuminate\View\View:renderContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:76
#18 Illuminate\View\View:render in
C:\xampp\htdocs\medifile_new\project\app\storage\views\7f78cbb3210065eb6917c361a84e3f5d:23
#17 include in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:37
#16 Illuminate\View\Engines\PhpEngine:evaluatePath in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:56
#15 Illuminate\View\Engines\CompilerEngine:get in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:134
#14 Illuminate\View\View:getContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:102
#13 Illuminate\View\View:renderContents in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\View\View.php:76
#12 Illuminate\View\View:render in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Http\Response.php:43
#11 Illuminate\Http\Response:setContent in
C:\xampp\htdocs\medifile_new\project\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php:202
#10 Symfony\Component\HttpFoundation\Response:__construct in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1423
#9 Illuminate\Routing\Router:prepareResponse in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:999
#8 Illuminate\Routing\Router:dispatchToRoute in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Routing\Router.php:964
#7 Illuminate\Routing\Router:dispatch in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:738
#6 Illuminate\Foundation\Application:dispatch in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:708
#5 Illuminate\Foundation\Application:handle in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Session\Middleware.php:72
#4 Illuminate\Session\Middleware:handle in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php:47
#3 Illuminate\Cookie\Queue:handle in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php:51
#2 Illuminate\Cookie\Guard:handle in
C:\xampp\htdocs\medifile_new\project\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in
C:\xampp\htdocs\medifile_new\project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:606
#0 Illuminate\Foundation\Application:run in
C:\xampp\htdocs\medifile_new\project\public\index.php:49

Call to undefined method Illuminate\Database\Query\Builder::user_profile()
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)
(View:
C:\xampp\htdocs\medifile_new\project\vendor\jacopo\laravel-authentication-acl\src\views\admin\layouts\partials\avatar.blade.php)

**Comment by intrip** [comment]
Did you setup the laravel public folder as the document root and enabled mod_rewrite?

**Comment by faithinna** [comment]
no

**Comment by intrip** [comment]
You should do that in order to properly setup the laravel environment, check out the install guide http://laravel.com/docs/4.2/quick
