### ISSUE TITLE
Incompatible with Postgres

### ISSUE THREAD

**Issue by klapifoch** [intrip/laravel-authentication-acl#6]
[Illuminate\Database\QueryException]  
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "`"                           
  LINE 1: ALTER TABLE`user_profile`ADD`avatar`LONGBLOB DEFAULT N...                        
 ^ (SQL: ALTER TABLE`user_profile`ADD`avatar` LONGBLOB DEFAULT NULL)

The problem is with this line:
https://github.com/intrip/laravel-authentication-acl/blob/master/src/migrations/2014_02_26_165011_create_user_profile_table.php#L37

I fixed using:
DB::statement('ALTER TABLE user_profile ADD avatar BYTEA DEFAULT NULL');

But why you don't use $table->binary('avatar') ?

Also after that when i try to log in under admin section i got this error:
exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42803]: Grouping error: 7 ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select "users"._, "user_profile"."first_name", "user_profile...
               ^ (SQL: select "users"._, "user_profile"."first_name", "user_profile"."last_name", "user_profile"."zip", "user_profile"."code", "groups"."name" from "users" left join "user_profile" on "users"."id" = "user_profile"."user_id" left join "users_groups" on "users"."id" = "users_groups"."user_id" left join "groups" on "users_groups"."group_id" = "groups"."id" group by "users"."email")'

https://github.com/intrip/laravel-authentication-acl/blob/master/src/Jacopo/Authentication/Repository/UserRepositorySearchFilter.php#L166

Are you just support mysql databases?

**Comment by intrip** [comment]
I offer support to all relational DBMS supported by eloquent so I'll fix that asap.

**Comment by klapifoch** [comment]
Ok thank you! I will wait to see this working in postgresql...

**Comment by intrip** [comment]
I found i couple of problem with postgres, i'll try to fix them asap. I'll tell you when i'm done.

**Comment by klapifoch** [comment]
What happened with this issue?

**Comment by intrip** [comment]
I was on vacation i'll fix it asap, :)

**Comment by intrip** [comment]
I've created major bugfixes and updated a new version compatible with postgres. Remember to update your _composer.json_ dependency to 1.1.\* and run _composer update_. Waiting for your feedback.

**Comment by klapifoch** [comment]
It is working now... Thank you!

**Comment by intrip** [comment]
You're welcome! Anytime :smile:
