### ISSUE TITLE
Illuminate \ Session \ TokenMismatchException

### ISSUE THREAD

**Issue by kamaroly** [intrip/laravel-authentication-acl#60]
I am getting below error , anyone to help on this ?

Route::filter('csrf', function()
{
    if (Session::token() !== Input::get('_token'))
    {
        throw new Illuminate\Session\TokenMismatchException;
    }
});

**Comment by intrip** [comment]
You should use form::token field in your form. In which page you're getting this error?

**Comment by kamaroly** [comment]
I am getting it on admin/login

**Comment by intrip** [comment]
Did you enable the capcha option and disabled javascript?

**Comment by kamaroly** [comment]
I saw the error, I was using php -S localhost:8000 -t public instead of artisan serve to serve the application
