### ISSUE TITLE
how can I echo the current logged in user

### ISSUE THREAD

**Issue by DHALE333** [intrip/laravel-authentication-acl#62]
How do I echo the current logged in user in a view??

thanks

**Comment by intrip** [comment]
echo $logged_user->email etc...

**Comment by Yolcar** [comment]
I'm trying to get user data in my custom view using: echo $ logged_user-> email, to try it throws me the following error

ErrorException thrown with message "Undefined variable: logged_user (View: C:\xampp\htdocs\laravel\app\views\navbar.blade.php) (View: C:\xampp\htdocs\laravel\app\views\navbar.blade.php)"

I solved using: echo Sentry::getUser()->email
