### ISSUE TITLE
BadMethodCallException to user_profile()

### ISSUE THREAD

**Issue by faithinna** [intrip/laravel-authentication-acl#63]
I get this error when i run  php artisan authentication:install

[BadMethodCallException]
 Call to undefined method Illuminate\Database\Query\Builder::user_profile()

PLEASE  help me fix this error 
 i am using mysql  from xampp

**Comment by intrip** [comment]
I've pushed a fix please let me know if the problem still persist.

**Comment by Andrew-Shook** [comment]
I'm getting this error as well
