### ISSUE TITLE
Trying to update avatar

### ISSUE THREAD

**Issue by fural** [intrip/laravel-authentication-acl#64]
Hello mate, when I tried to update the avatar, I got this error:

SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0x89 (SQL: update "user_profile" set "avatar" = �PNG  IHDR�� .....   

My database encoding is UTF8 and database.php is configured as pgsql and the same encoding.

**Comment by intrip** [comment]
Strange, did you try with other images aswell or is not working for any image?

**Comment by fural** [comment]
Yes, I did... I tried with lots of images and still happening.

**Comment by intrip** [comment]
Your database is utf-8 unicode?

**Comment by chrizz1001** [comment]
The DB field has the right type?
