### ISSUE TITLE
Sentry config not loaded from app/config/... dir

### ISSUE THREAD

**Issue by chrizz1001** [intrip/laravel-authentication-acl#66]
Hi, I try to extend the jacopo user model but it looks like the sentry config files are not loaded correctly. I have the config files located in <code>app/config/packages/jacopo/laravel-authentication-acl</code> . the authentication config files are loaded correctly (if I change something it works) but when I try to edit the sentry config (to load my user model) it doesn't work. For testing I changed the sentry config in the jacopo library to see if it works there (it works). Would be nice not to change the authentication library for using my model.

**Comment by intrip** [comment]
You have to edit the app/config/packages/jacopo/laravel-authentication-acl/sentry/config.php file.

**Comment by chrizz1001** [comment]
I have created an extension in workbench folder and included authentication via composer file in my package. I also noticed that the wrong config files was loaded. My workaround is do Load and overwrite the config information manually in my service providers register function. 

```
    /**
     * Port config for laravel-authentication-acl
     */
    // Get config loader
    $loader = $this->app['config']->getLoader();

    // Get environment name
    $env = $this->app['config']->getEnvironment();

    // Add package namespace with path set base on your requirement
    $loader->addNamespace('laravel-authentication-acl',__DIR__.'/../../../../../../app/config/packages/jacopo/laravel-authentication-acl');

    // Load package override config file
    $configs = $loader->load($env,'config','laravel-authentication-acl');

    // Override value
    $this->app['config']->set('laravel-authentication-acl::config',$configs);
```

This way you don't need to touch the auth package files, so they remain update save

**Comment by misterx** [comment]
Other way, create new service in app/services/

``` php

namespace Services;
use Illuminate\Support\ServiceProvider;

class AuthenticationServiceProvider extends ServiceProvider
{
    public function register()
    {

    }

    public function boot()
    {
        parent::boot();
        //Fix sentry user config load
        $this->app['config']->getLoader()->addNamespace('cartalyst/sentry', __DIR__ . '/../config/packages/jacopo/laravel-authentication-acl/sentry');
    }

}
```

And in config/app.php add this service after Jacopo\Authentication\AuthenticationServiceProvider

``` php
'Jacopo\Authentication\AuthenticationServiceProvider',
'Services\AuthenticationServiceProvider',
```
