### ISSUE TITLE
can't setup on clean laravel base table or view not found permission

### ISSUE THREAD

**Issue by bartwind** [intrip/laravel-authentication-acl#67]
On package instal:
php artisan authentication:install

[Illuminate\Database\QueryException]  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdb.permission' doesn't exist (SQL: i  
  nsert into `permission` (`description`, `permission`, `updated_at`, `created_at`) values (superadmin, _su  
  peradmin, 2015-01-12 21:30:30, 2015-01-12 21:30:30))    

[PDOException]  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdb.permission' doesn't exist 

config files are set, default db clean empty mysql connection

migrations are not done ... installed on current clean laravel 4

**Comment by intrip** [comment]
Did you create and empty db called testdb ?

**Comment by bartwind** [comment]
Yes. From is this insert? On clean DB at first priority should be run creating migrations why there isnt?

**Comment by bartwind** [comment]
creating tables migrations

**Comment by intrip** [comment]
You have to:
1) Create a new **empty** database
2) run install script

**Comment by bartwind** [comment]
It's not working i have empty new databse and have proper config in database.php in my main config and php artisan authentication:install not working.

**Comment by intrip** [comment]
did you setup your database.php file in laravel and which version of php you using? Please post the full error message here

**Comment by bartwind** [comment]
New project clean laravel + installed ACL package, default databse mysql in app/config/database.php wich is empty
![laravelacl](https://cloud.githubusercontent.com/assets/10350813/5748503/c24792e6-9c40-11e4-953a-67690a8827b3.png)

**Comment by chrizz1001** [comment]
Maybe the DB user has no rights to create tables or some permission problems for writing extension files?

**Comment by bartwind** [comment]
It's root user i set chmod 0777 for project files

**Comment by chrizz1001** [comment]
And your Databases user rights? Maybe it's forbidden for him to create tables

**Comment by bartwind** [comment]
I have all rights I can create tables

**Comment by intrip** [comment]
I tryed that with the latest laravel 4.2 and worked, did you press y on the question do you wish to run this command? because i see command cancelled on screenshoot. Also remember you need to run the install command only once.

**Comment by bartwind** [comment]
My fail yeah I don't type 'y'. Thanks for help.
Regards
