### ISSUE TITLE
Overwrites DB connection used by Laravels validator

### ISSUE THREAD

**Issue by philippzentner** [intrip/laravel-authentication-acl#68]
Hey,

i am not able to use Laravels validator anymore as it uses the database i separately specified for the ACL. I had to do this as your packages migrations do not support UTF8mb4 databases.
Now i do not want to overwrite the validators connection anytime i use it.

Any idea on how to work around? Otherwise i'd have to fork the project and make the migrations utf8mb4 compatible (just reducing some field-lengths).

Best
Phil

**Comment by philippzentner** [comment]
I could solve it by:
1. Use the possibility to publish your packages configs and giving the db-connection a name "authentication"
2. Explicitly set the connection-name of the validator in App::before filter

$verifier = App::make('validation.presence');
$verifier->setConnection('mysql');

This is not a solution on long-term or scale

**Comment by intrip** [comment]
I don't think i would change the migration to with with UTF8mb4 by reducing the length of some fields.
You problem is that you cannot use validator with every model in your app of just with the package models? could you give me an example?

**Comment by philippzentner** [comment]
The utf8 thing is another problem. It is the reason why i chose to create another DB for this ACL.
And therefore i would have to change the length of the fields (it is because mb4 needs more bytes per char (4 instead of 3). I need utf8mb4 for saving data like emoticons. (This here describes the issue: http://stackoverflow.com/questions/6172798/mysql-varchar255-utf8-is-too-long-for-key-but-max-length-is-1000-bytes)

But back to the validator problem: I don't know what happens. It seems that when i specify an extra database for your package, it overwrites the validation.presence connection which makes it unusable.

As you can see in the solution above: when i reset it to the normal db-connection, it works again.

**Comment by intrip** [comment]
Allright, i'll take a look then.

**Comment by philippzentner** [comment]
Great, thanks. Keep up the good work. I really prefered your ACL as i can jump in and start focusing on creating the things i need instead of the things around it (design, structure, etc.).
