### ISSUE TITLE
once logged in, Redirect to Route::intended()

### ISSUE THREAD

**Issue by adamriggsy** [intrip/laravel-authentication-acl#69]
Is it possible to redirect to the referring page once a user is logged in? Sorry if I am overlooking something simple.

**Comment by intrip** [comment]
Did you check the docs? https://github.com/intrip/laravel-authentication-acl/blob/1.2/docs/index.md#advanced check "How to hide access on a given url to anonymous user?"

**Comment by adamriggsy** [comment]
I am not seeing how that answers my question. Here is the flow I am looking for:
1. Anonymous user visits page (domain.com/about) that requires login and is redirected to domain.com/user/login
2. User provides login information and is logged into the site.
3. User then gets redirected to domain.com/about

This flow should work the same on all pages that are protected by login, (i.e. domain.com/about, domain.com/history or domain.com/offers)

**Comment by intrip** [comment]
You should use the logged filter to redirect users to a given page if they are not logged in, like that:

``````
Route::get('check_custom', [
'before' => "logged:/custom_url",
'uses' => function(){
     // put your code here
}]);```
``````

**Comment by adamriggsy** [comment]
Ok. Thanks.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
