### ISSUE TITLE
Vary contents of Views based on permissions

### ISSUE THREAD

**Issue by imyque** [intrip/laravel-authentication-acl#71]
Hello Intrip,

I just found this project last night. Thank you a million times for this wonderful project. It is going to save me a lot of hard work.

Please I need you help with these questions;
1) Is there a way for me to, for instance, hide/show a menu item or a portion of a  Blade template based on permission.
2) Is there a way for me to test for a logged in user's permission the controller to determine the flow of control?

Thanks

**Comment by intrip** [comment]
Hello, you can use the following code to get the logged user:

``` php
App::make('authenticator')->getLoggedUser()
```

The user have a permissions array that belongs to him so that you can check for the desired permissions
Hope that solves your problem.
Feel free to ask me further details.
