### ISSUE TITLE
how to add new users in a controller

### ISSUE THREAD

**Issue by wtdragon** [intrip/laravel-authentication-acl#75]
Hi Intrip,
I want to use a excel api upload lots of users with some permission.
Then under the controller to add them,is there any  method to do that.

Thanks&Regards

**Comment by intrip** [comment]
Could you be more precise about what you need to do?

**Comment by wtdragon** [comment]
ok.
There's two table and model I created, one is tearcher another is student.
In the ACL with two permission, one is _teacher anboter is _student.
When I created students or a teachers, also want create users use laravel-authentication-acl api.
That is I want,is it clear enough?
Thanks&Regards.

**Comment by intrip** [comment]
You need to create new routes and add them to routes.php, then you can use the filter. The filter now uses cookie authentication so if you want to use a token authentication for now it's not supported.
