### ISSUE TITLE
2nd questions how to change the login redirect

### ISSUE THREAD

**Issue by wtdragon** [intrip/laravel-authentication-acl#76]
Hi Intrip,
in the config.php default url after login is redirect to "/".
Could I change it to stay at the same page as user login?
Thanks&Regards

Gavin

**Comment by wtdragon** [comment]
change the method in AuthController with permission find

**Comment by intrip** [comment]
Yes you can, you need to override the package default configuration. Check out the docs about that.

**Comment by wtdragon** [comment]
thanks a lot for your help. how about the last question, is there any method can use to create user directly?

**Comment by intrip** [comment]
You need to use The User class: new User($attributes)->save();
