### ISSUE TITLE
Includes file exception

### ISSUE THREAD

**Issue by mvatansever** [intrip/laravel-authentication-acl#78]
I have installed Laravel 5.0.\* and acl 1.3 version but i have get installation error when install acl. type terminal the command: 
`sudo php artisan authentication:install`

And i get this error:

PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers/menu.php): failed to open stream: No such file or directory' in /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers.php:2
Stack trace:
#0 /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers.php(2): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/var/www/html/l...', 2, Array)
#1 /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers.php(2): require()
#2 /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/AuthenticationServiceProvider.php(54): require('/var/www/html/l...')
#3 [internal function]: LaravelAcl\Authentication\AuthenticationServiceProvider->boot()
#4 /var in /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers.php on line 2

PHP Stack trace:
PHP   1. {main}() /var/www/html/laravel-egitim-project/laravel/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/html/laravel-egitim-project/laravel/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:92
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:195
PHP   5. Illuminate\Foundation\Bootstrap\BootProviders->bootstrap() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:181
PHP   6. Illuminate\Foundation\Application->boot() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php:15
PHP   7. array_walk() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:686
PHP   8. Illuminate\Foundation\Application->Illuminate\Foundation{closure}() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:686
PHP   9. Illuminate\Foundation\Application->bootProvider() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:685
PHP  10. Illuminate\Container\Container->call() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:703
PHP  11. call_user_func_array() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:523
PHP  12. LaravelAcl\Authentication\AuthenticationServiceProvider->boot() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:523
PHP  13. require() /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/AuthenticationServiceProvider.php:54
PHP Fatal error:  main(): Failed opening required '/var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers/menu.php' (include_path='/var/www/html/laravel-egitim-project/laravel/vendor/phpunit/php-text-template:/var/www/html/laravel-egitim-project/laravel/vendor/phpunit/php-timer:.:/usr/share/php:/usr/share/pear') in /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/composers.php on line 2
PHP Stack trace:
PHP   1. {main}() /var/www/html/laravel-egitim-project/laravel/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /var/www/html/laravel-egitim-project/laravel/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:92
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:195
PHP   5. Illuminate\Foundation\Bootstrap\BootProviders->bootstrap() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:181
PHP   6. Illuminate\Foundation\Application->boot() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php:15
PHP   7. array_walk() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:686
PHP   8. Illuminate\Foundation\Application->Illuminate\Foundation{closure}() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:686
PHP   9. Illuminate\Foundation\Application->bootProvider() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:685
PHP  10. Illuminate\Container\Container->call() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:703
PHP  11. call_user_func_array() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:523
PHP  12. LaravelAcl\Authentication\AuthenticationServiceProvider->boot() /var/www/html/laravel-egitim-project/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:523
PHP  13. require() /var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/AuthenticationServiceProvider.php:54

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  main(): Failed opening required '/var/www/html/laravel-egitim-project/laravel/vendor/jacopo/laravel-authentication-acl/app/Authent  
  ication/composers/menu.php' (include_path='/var/www/html/laravel-egitim-project/laravel/vendor/phpunit/php-text-template:/var/www/  
  html/laravel-egitim-project/laravel/vendor/phpunit/php-timer:.:/usr/share/php:/usr/share/pear')                                     

Cause of this error is wrong path name.  
Fix of this bug:
You wanna go and edit this file: laravel/vendor/jacopo/laravel-authentication-acl/app/Authentication/Composers/menu.php and edit your file paths like this:

```
<?php
require __DIR__ . '/Composers/menu.php';

require __DIR__ . '/Composers/select_items.php';

require __DIR__ . '/Composers/dashboard.php';

require __DIR__ . '/Composers/permissions.php';

require __DIR__ . '/Composers/others.php';
```

**Comment by intrip** [comment]
Thanks for the info, i think it's fixed now. Try again and tell me.
