### ISSUE TITLE
Permissions issue in Admin area

### ISSUE THREAD

**Issue by andreas22** [intrip/laravel-authentication-acl#8]
Hi,

I have created a new page in admin area and a new permission just for that page. Also I have created a new user which has only permissions to that page and no any other permissions. 

The problem:
When the new user login to admin, is redirected to /admin/users/dashboard by default  as a result he sees an error message of insufficient permissions.

Proposed solution:
Make a dashboard which all logged in users in admin area will have access and will be redirected once login, and once they are in admin they will see only the menu items they have permissions to it :)

This is very essential for any admin area, as you will have users of different permissions that will need to perform different kind of tasks.

**Comment by intrip** [comment]
Ok i'll take a look at it

**Comment by intrip** [comment]
I've fixed that by creating a dashboard link available to all users, i've also added a method in FileRouteHelper class (hasPermForRoute) that checks if current user has a give permission to a route.
Waiting for your feedback. Remember to update your _composer.json_ file dependency to 1.1.\* and to run _composer update_

**Comment by andreas22** [comment]
I have added a new permission to a user and he can login and redirects to dashboard with success, and I can see the item 
I gave permissions, when enter the specific menu item I see my list of items as expected. 
But I have edit links and add new that I have set permissions only to superadmin as shown below and still the logged user can access them.
Why is that?

[
    "name" => "Data",
    "route" => "data",
    "link" => URL::route('data.list'),
    "permissions" => ["_superadmin", "_test"]
],
[
    "name" => "",
    "route" => "data",
    "link" => URL::route('data.new'),
    "permissions" => ["_superadmin"]
],
[
    "name" => "",
    "route" => "data",
    "link" => URL::route('data.edit'),
    "permissions" => ["_superadmin"]
],

Secondly, I gave permissions to a new user [profile type editor] but when logins in admin cannot see the link to edit profile on top right, only logout
option is shown.

**Comment by intrip** [comment]
Answer to first question: the permission in the admin menu at the moment are based on the "route" parameter(not the link) and in this example the route parameter is the same. 
Answer to second question: the user cannot edit profile because he doesn't have the permission to edit user profiles for this reason the link his hidden. The idea is to have a public part in the website where the user edit his profile and not thru the admin panel. But if you have any tips i'll appreciate that.

**Comment by andreas22** [comment]
It would be great if a user that has permissions to access admin, to be able to modify its profile. Because in admin area u can have different functionality that users will have access to it but they will not be superadmins neither they will have permissions to users/groups/permissions.

**Comment by intrip** [comment]
I'll fix that in next release.

**Comment by andreas22** [comment]
thanks

**Comment by intrip** [comment]
I've changed the software now, every user can edit his own profile.
I've also added a _skip_permissions_ field in _menu.php_ that allow you to skip permission check for a given route under the same namespace (e.g. users.profile)
