### ISSUE TITLE
ReflectionException in Container.php line 776:

### ISSUE THREAD

**Issue by sinabio** [intrip/laravel-authentication-acl#80]
hello,

when i clicked to edit permission get following error:

url: http://localhost/admin/permissions/edit?id=1
#### error:

  1/1 ReflectionException in Container.php line 776:
  Class LaravelAcl\Authentication\Controllers\PermissionController does not exist

**Comment by bryce-mullican** [comment]
around line 219 in \vendor\jacopo\laravel-authentication-acl\app\Http\routes.php there are too many slashes. Fixed it for me.

**Comment by intrip** [comment]
Should be fixed now, tell me if find any other problems
