### ISSUE TITLE
Type error?

### ISSUE THREAD

**Issue by bart-heideman** [intrip/laravel-authentication-acl#82]
Nice ACL!

I've noticed a type error in your other routes. You are returning viw instead of view.

https://github.com/intrip/laravel-authentication-acl/blob/1.3/app/Http/routes.php

Edit: it's not only the other routes, it's everywhere in the routes file you are returning viw instead of view.

Best,

Bart

**Comment by intrip** [comment]
Thanks for the tip, should be fixed now. Tell me if you find any other problem!
