### ISSUE TITLE
Laravel 5.1.* dependency error.

### ISSUE THREAD

**Issue by josearodrigueze** [intrip/laravel-authentication-acl#84]
I am trying to use your library which is excellent according to documentation but when I try to install my project with composer throws me the following error:

_Your requirements could not be resolved to an installable set of packages._

> Problem 1
>     >>- jacopo/laravel-authentication-acl 1.3.0 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.1 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.2 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.3 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.4 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.5 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.6 requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- jacopo/laravel-authentication-acl 1.3.x-dev requires laravel/framework 5.0.\* -> satisfiable by laravel/framework[5.0.x-dev].
>     >>- Conclusion: don't install laravel/framework 5.0.x-dev
>     >>- Installation request for jacopo/laravel-authentication-acl 1.3.\* -> satisfiable by jacopo/laravel-authentication-acl[1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.x-dev].

**Comment by intrip** [comment]
Sorry but i'm not planning to make this package to work with development version of Laravel, I'm only supporting the latest stable version of Laravel which is 5.0 for now

**Comment by firsara** [comment]
Hi, got the same problem when trying to install on a fresh 5.1 laravel installation:
- jacopo/laravel-authentication-acl 1.3.9 requires laravel/framework 5.0.\* -> no matching package found.

5.1 should be stable as of now, can you explain?

**Comment by murbanowicz** [comment]
5.1 is stable and LTS.
Can you do something?

**Comment by intrip** [comment]
I'ts working with 5.1 now.
