### ISSUE TITLE
does it have registration wizard functionality?

### ISSUE THREAD

**Issue by chriz74x** [intrip/laravel-authentication-acl#87]
does this package has wizard registration capability? I mean user first insert required fields like email / username / password then he hits the NEXT button and a new page asks him for additional data (example sex / age / whatever) at this point when everything is filled the user submits the registration, the package so inserts the first data into users table and the details of the second page in a user_datas table or something. Is it possible with this?

**Comment by intrip** [comment]
No it doesn't sorry.
