### ISSUE TITLE
Could you make site-user part optional?

### ISSUE THREAD

**Issue by alexglue** [intrip/laravel-authentication-acl#91]
What if i wanna just an /admin interface? could you move this features as stand-alone optional part? Or how can i disable it?

**Comment by strixy** [comment]
It's possible to separate it out if you use the permissions system eg. only those users with the permission "superadmin" will be allowed in to /admin. A little creative work with routes.php to match your specific case and you'll be fine. It's pretty easy, but the work is unique for each site.

**Comment by intrip** [comment]
As strixy says you can handle that with permissions.
