### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by strixy** [intrip/laravel-authentication-acl#92]
I'm not sure if I'm the only one experiencing this as there are no open issues associated to 'pagination'. I appear to be having pagination issues so I thought I would check if anyone else experienced this issue?  In the admin section, the users table shows all users. The pagination links are visible and they manipulate the page get parameter just fine, but there appears to be no actual pagination happening. ie. I have 22 users and on page 1 it shows all users (22 not 15) and if you click on page two it continues to show all users (22 not 7).

I know that I can paginate the results accordingly when I change

$users = $q->get();
to
$users = $q->paginate($this->per_page)->all();

in UserRepositorySearchFilers.php

BUT that makes use of the query builder Paginator and not the package paginator which then breaks the view presenter for pagination. ie. the paginator links disappear. 

versions Laravel 4.2 and acl 1.2

**Comment by intrip** [comment]
Could you please provide me the alc tag you're using and the laravel version (4.2.x)?

**Comment by strixy** [comment]
This could just be me. I don't know if anyone else can reproduce this. 

laravel/framework = v4.2.17
the acl is my fork of 1.2 (forked January 22nd)
(Link to diff https://github.com/intrip/laravel-authentication-acl/compare/1.2...strixy:1.2)

**Comment by intrip** [comment]
I'm sorry but i can't afford to mantain Laravel 4 version anymore.
