### ISSUE TITLE
Copy Acl-admin file totapp folder ?

### ISSUE THREAD

**Issue by annaCD** [intrip/laravel-authentication-acl#93]
After installation All admin section files in the vendor section. How to copy to main app section ?

**Comment by jacopo-beschi-intersail** [comment]
php artisan vendor:publish --force

**Comment by techguydev** [comment]
Hello Jacopo!,

Thanks a lot for  such a  great  package!, it helps a lot to  save  time on projects.

I tried php artisan vendor:publish --force

 Although the route.php  file in app/http is not showing the routes for the authentication system, if  we need to add some new permission or change something we  still need to update it  in vendor/jacopo/laravel-authentication-acl/http/routes.php

how  can migrate this  to the  main  route in the sytem app/http/route.php

Same  thing  for the  controllers and models

Thanks

**Comment by intrip** [comment]
You can override the routes and models in your app/models folder, you don't need to publish them in this case.

**Comment by techguydev** [comment]
Excellent!, thansks a lot.

**Comment by techguydev** [comment]
Ah alright!, excellent!,  thanks a lot !.

2015-06-15 15:09 GMT-04:30 jacopo notifications@github.com:

> You can override the routes and models in your app/models folder, you
> don't need to publish them in this case.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/intrip/laravel-authentication-acl/issues/93#issuecomment-112183286
> .

## 

Cordialmente ,

_Ing. Luis Antonio Mata B._
Skype:luisantoniomata
Phone: 005804249547643
_Necesita una pagina web?_
*visitenos: *http://www.sistechma.com/
http://ve.linkedin.com/in/luisantoniomata
