### ISSUE TITLE
The user can access as admin

### ISSUE THREAD

**Issue by TheBestMovieIsYourImagination** [intrip/laravel-authentication-acl#95]
I noticed the user can access as admin. He can see the admin dashboard with the number of total users, active, pending and banned users, althought he can't make changes.

**Comment by intrip** [comment]
this depends on the configuration of the acl_menu.php, you can add a custom permission to access the dashboard, in that case only user with that permission can access it. check out the docs for the route permission for more info. here is the line you need to edit:

"list" => [
            [
                    "name"        => "Dashboard",
                    "route"       => "dashboard",
                    "link"        => '/admin/users/dashboard',
                    "permissions" => []
            ],

**Comment by TheBestMovieIsYourImagination** [comment]
a really quick answer, thanks! :)
