### ISSUE TITLE
How to access the groups that a user belongs

### ISSUE THREAD

**Issue by techguydev** [intrip/laravel-authentication-acl#96]
Hello, have been testing your laravel- authentication-acl package and it is very  good.

In the view admin.user.user-table.blade.php  I am trying to add a  new  column  which  shows the groups that each user belongs to but I am getting errors.

I can see that in the  admin.user.groups.blade.php is implementing a  way to  show each user's group but when I  try to use such approach in the admin.user-table.blade.php it  tells me  that the variable $groups does not exist, I checked that and I realized that  it is passed to the  view from the groups controller like this:

   public function getList()
    {
        $groups = $this->group_repository->all(Input::all());

```
    return View::make('laravel-authentication-acl::admin.group.list')->with(["groups" => $groups]);
}
```

I tried to do the  same in the user controller: 

  public function getList()
    {
        $users = $this->user_repository->all(Input::except(['page']));

```
    $groups = $this->group_repository->all(Input::all());

    return View::make('laravel-authentication-acl::admin.user.list')->with(["users" => $users,"groups" => $groups ]);

}
```

So I can allow the admin.user.user-table.blade.php to have the $groups, I am  trying to get is data like this:

```
@foreach($user->groups as $group)
  {!! Form::open(["route" => "users.groups.delete", "role"=>"form", 'name' => $group->id]) !!}
                                  <div class="form-group">
                                      <div class="input-group">
                                          <span class="input-group-addon form-button button-del-group" name="{!! $group->id !!}"><span class="glyphicon glyphicon-minus-sign add-input"></span></span>
                                          {!! Form::text('group_name', $group->name, ['class' => 'form-control', 'readonly' => 'readonly']) !!}
                                          {!! Form::hidden('id', $user->id) !!}
                                          {!! Form::hidden('group_id', $group->id) !!}
                                      </div>
                                  </div>
                                  {!! Form::close() !!}
```

But I am  getting this  error:

ErrorException in UserController.php line 63:
Undefined property: LaravelAcl\Authentication\Controllers\UserController::$group_repository

How shoulded this be implemented?

Thanks a lot

**Comment by intrip** [comment]
In the constructor of the GroupsController there is this line of code:
        $this->group_repository = App::make('group_repository');
With that like you initialize the group repository, if you want to use it on the UserController you need to do the same in his constructor.

**Comment by techguydev** [comment]
I made the  changes but I  am still getting  this error:

ErrorException in dfbf4634c4ba8e21af6a13ae2d0e49cf line 57:
Undefined property: stdClass::$groups (View: /var/www/laravel/resources/views/vendor/laravel-authentication-acl/admin/user/user-table.blade.php) (View: /var/www/laravel/resources/views/vendor/laravel-authentication-acl/admin/user/user-table.blade.php)
