### ISSUE TITLE
No vendor storage

### ISSUE THREAD

**Issue by cstpraveen** [intrip/laravel-authentication-acl#97]
When I try to use it shows the below error

Warning: require(/var/www/html/laravel/laravel-authentication/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/laravel/laravel-authentication/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/html/laravel/laravel-authentication/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/laravel/laravel-authentication/bootstrap/autoload.php on line 17

**Comment by intrip** [comment]
What version of Laravel are you using? Laravel itself was working correctly?
