### ISSUE TITLE
It seems it is not compatible yet with Laravel above 5.0

### ISSUE THREAD

**Issue by alvaritoe** [intrip/laravel-authentication-acl#98]
From what I am seeing, this problem also existed in the past and it needed to update the dependencies of the ACL library, once they were updated, then ACL worked with Laravel 4.2. But it seems to me that the problem has reproduced again with the latest version of Laravel 5.1\* so, it will be a matter of doing the same fixes as before. Here is the issue:

On adding this:

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._",
         "jacopo/laravel-authentication-acl": "1.3._"

I am running development mode, but if put the instruction in require-dev, I get the same error, no difference.       

Besides, in the latest installation instructions, I think there is a small error:

where it says:
1. And now run composer install, it should say, run composer update

I get this:

jacopo/laravel-authentication-acl 1.3.9 requires laravel/framework 5.0.\* -> no matching package found.
    - jacopo/laravel-authentication-acl 1.3.8 requires laravel/framework 5.0.\* -> no matching package found.

the list goes down to 1.3.8, 1.3.7 etc

 Installation request for jacopo/laravel-authentication-acl 1.3.\* -> satisfiable by jacopo/laravel-authentication-acl[1.3.0, 1.3.1, 1.3.10, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

since I am running KLarave 5.1.6

If I try to install the dev-master version, then I get

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: remove laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Installation request for jacopo/laravel-authentication-acl dev-master -> satisfiable by jacopo/laravel-authentication-acl[dev-master].
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - jacopo/laravel-authentication-acl dev-master requires illuminate/support ~4 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.1.0

this has happened to me on my webservr hosting as well as my local linux.

**Comment by intrip** [comment]
Working on it

**Comment by muhx** [comment]
Waiting for this solution

**Comment by intrip** [comment]
I've pushed a new version that works also with Laravel 5.1. Please take a look and give me some feedback.
