### ISSUE TITLE
When trying to view Profiles the follow error occurs

### ISSUE THREAD

**Issue by dodwmd** [intrip/laravel-authentication-acl#99]
URL:- /admin/users/profile/self

ErrorException in Application.php line 666:
Argument 2 passed to Illuminate\Foundation\Application::make() must be of the type array, string given, called in <edited>/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 213 and defined

**Comment by intrip** [comment]
Which version of laravel are you using?

**Comment by dodwmd** [comment]
Laravel 5.1

**Comment by techguydev** [comment]
I  have tried it  in  Laravel  5.0 and it works  like a charm!, I suggest
 to consider it.

2015-07-17 19:39 GMT-04:30 Michael Dodwell notifications@github.com:

> Laravel 5.1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/intrip/laravel-authentication-acl/issues/99#issuecomment-122458861
> .

## 

Cordialmente ,

_Ing. Luis Antonio Mata B._
Skype:luisantoniomata
Phone: 005804249547643
_Necesita una pagina web?_
*visitenos: *http://www.sistechma.com/
http://ve.linkedin.com/in/luisantoniomata

**Comment by jacopo-beschi-intersail** [comment]
I still need to do some chabges to make it work with laravel 5.1

**Comment by intrip** [comment]
I've pushed a new version that works also with Laravel 5.1. Please take a look and give me some feedback.

**Comment by dodwmd** [comment]
Will do, thanks!
